'use client'

/**
 * ProcedureChecklistExport — print-friendly export of document checklist.
 *
 * Opens a lightweight print window with a styled A4 page showing:
 *   - Procedure title
 *   - Document list with ✅ / ☐ status (reads dalilak_doc_{code}_{i})
 *   - Expiry dates if set (reads dalilak_doc_expiry_{code}_{i})
 *   - Dalilak branding footer
 *
 * Uses window.open() + print() — works on mobile too (shares/prints from browser).
 *
 * Props: { code: string; docs: string[]; titleAr: string; titleEn?: string; isAr: boolean }
 */

import React, { useState } from 'react'

interface Props {
  code: string
  docs: string[]
  titleAr: string
  titleEn?: string
  isAr: boolean
}

function loadCheckState(code: string, count: number): boolean[] {
  try {
    return Array.from({ length: count }, (_, i) =>
      localStorage.getItem(`dalilak_doc_${code}_${i}`) === '1'
    )
  } catch { return Array(count).fill(false) }
}

function loadExpiries(code: string, count: number): string[] {
  try {
    return Array.from({ length: count }, (_, i) =>
      localStorage.getItem(`dalilak_doc_expiry_${code}_${i}`) || ''
    )
  } catch { return Array(count).fill('') }
}

export default function ProcedureChecklistExport({ code, docs, titleAr, titleEn, isAr }: Props) {
  const [printing, setPrinting] = useState(false)

  function doExport() {
    const checked  = loadCheckState(code, docs.length)
    const expiries = loadExpiries(code, docs.length)
    const title    = isAr ? titleAr : (titleEn || titleAr)
    const dir      = isAr ? 'rtl' : 'ltr'
    const today    = new Date().toLocaleDateString(isAr ? 'ar-LB' : 'en-GB', { year: 'numeric', month: 'long', day: 'numeric' })
    const doneCount = checked.filter(Boolean).length

    const rows = docs.map((doc, i) => {
      const exp = expiries[i]
      return `
        <tr style="border-bottom:1px solid #F0E8E0;">
          <td style="padding:10px 8px;font-size:13px;width:30px;text-align:center;">${checked[i] ? '✅' : '☐'}</td>
          <td style="padding:10px 8px;font-size:13px;color:#292524;">${doc}</td>
          <td style="padding:10px 8px;font-size:11px;color:${exp ? '#92400E' : '#A8A29E'};text-align:${isAr ? 'left' : 'right'};">
            ${exp || '—'}
          </td>
        </tr>`
    }).join('')

    const html = `<!DOCTYPE html>
<html dir="${dir}" lang="${isAr ? 'ar' : 'en'}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@400;600;700;800&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'IBM Plex Sans Arabic',Arial,sans-serif; direction:${dir}; padding:32px 36px; color:#1C1917; background:#fff; }
  h1 { font-size:20px; font-weight:800; color:#8F1D2C; margin-bottom:6px; }
  .meta { font-size:11px; color:#78716C; margin-bottom:20px; }
  .progress { font-size:13px; font-weight:700; color:#065F46; background:#ECFDF5; border:1.5px solid #A7F3D0; border-radius:8px; display:inline-block; padding:4px 12px; margin-bottom:20px; }
  table { width:100%; border-collapse:collapse; }
  th { font-size:11px; font-weight:700; color:#78716C; padding:8px; background:#F9F7F5; border-bottom:2px solid #E5E0D8; }
  tr:last-child td { border-bottom:none; }
  .footer { margin-top:32px; text-align:center; font-size:10px; color:#A8A29E; border-top:1px solid #F0E8E0; padding-top:14px; }
  @media print { body { padding:20px; } }
</style>
</head>
<body>
<h1>${title}</h1>
<div class="meta">${isAr ? 'تاريخ الطباعة:' : 'Printed:'} ${today} — dalilak.vercel.app</div>
<div class="progress">${isAr ? `${doneCount} من ${docs.length} وثيقة جاهزة` : `${doneCount} of ${docs.length} documents ready`}</div>
<table>
  <thead>
    <tr>
      <th style="width:30px;"></th>
      <th style="text-align:${isAr ? 'right' : 'left'}">${isAr ? 'الوثيقة' : 'Document'}</th>
      <th style="text-align:${isAr ? 'left' : 'right'}">${isAr ? 'تاريخ الانتهاء' : 'Expiry'}</th>
    </tr>
  </thead>
  <tbody>${rows}</tbody>
</table>
<div class="footer">
  ${isAr ? 'أُنجز بمساعدة دليلك — مساعدك للمعاملات الحكومية اللبنانية' : 'Generated by Dalilak — Your Lebanese government procedures assistant'}
</div>
<script>window.onload = function(){ window.print(); }<\/script>
</body>
</html>`

    const win = window.open('', '_blank', 'noopener,noreferrer,width=800,height=700')
    if (!win) { alert(isAr ? 'يرجى السماح بالنوافذ المنبثقة' : 'Please allow popups'); return }
    win.document.write(html)
    win.document.close()
    setPrinting(true)
    setTimeout(() => setPrinting(false), 2000)
  }

  if (docs.length === 0) return null

  return (
    <button
      type="button"
      onClick={doExport}
      dir={isAr ? 'rtl' : 'ltr'}
      style={{
        display: 'inline-flex', alignItems: 'center', gap: 5,
        padding: '4px 10px', borderRadius: 16,
        background: printing ? '#ECFDF5' : '#F5F3EE',
        border: `1.5px solid ${printing ? '#A7F3D0' : '#E5E0D8'}`,
        cursor: 'pointer', fontFamily: 'inherit',
        fontSize: 10, fontWeight: 700,
        color: printing ? '#065F46' : '#5C534A',
        transition: 'all 0.2s',
      }}
      onMouseEnter={e => !printing && (e.currentTarget.style.background = '#EDE9E3')}
      onMouseLeave={e => !printing && (e.currentTarget.style.background = '#F5F3EE')}
    >
      {printing ? (
        <><span>✅</span>{isAr ? 'تم الفتح!' : 'Opened!'}</>
      ) : (
        <>
          <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
            <polyline points="6 9 6 2 18 2 18 9"/>
            <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/>
            <rect x="6" y="14" width="12" height="8"/>
          </svg>
          {isAr ? 'طباعة القائمة' : 'Print checklist'}
        </>
      )}
    </button>
  )
}
