import type { ProcedureFlowchart } from './knowledgeGraph'

export const FLOWCHARTS: Record<string, ProcedureFlowchart> = {
  'property-sale': {
    procedureSlug: 'property-sale',
    titleAr: 'بيع عقار',
    titleEn: 'Property Sale',
    country: 'lebanon',
    version: '1.0',
    verificationStatus: 'partially_verified',
    estimatedDurationAr: '4-8 أسابيع',
    estimatedDurationEn: '4-8 weeks',
    nodes: [
      { id: 'start', type: 'start', titleAr: 'بداية معاملة بيع العقار', titleEn: 'Start Property Sale', status: 'current' },
      { id: 'docs', type: 'document', titleAr: 'تجهيز المستندات', titleEn: 'Prepare Documents', status: 'not_started', descriptionAr: 'سند الملكية، هوية البائع والمشتري، مخطط العقار', requiredDocuments: ['سند الملكية', 'هوية شخصية', 'مخطط العقار', 'قيد عائلي'] },
      { id: 'notary', type: 'authority', titleAr: 'مراجعة الكاتب العدل', titleEn: 'Visit Notary', status: 'not_started', relatedAuthority: 'notary-public' },
      { id: 'contract', type: 'action', titleAr: 'إبرام عقد البيع', titleEn: 'Sign Sale Contract', status: 'not_started', riskLevel: 'high' },
      { id: 'risk_check', type: 'risk', titleAr: 'تحقق من بند الضمان', titleEn: 'Verify Guarantee Clause', status: 'not_started', descriptionAr: 'تأكد من وجود بند الضمان وعدم وجود رهون' },
      { id: 'registry', type: 'authority', titleAr: 'التسجيل في السجل العقاري', titleEn: 'Register in Land Registry', status: 'not_started', relatedAuthority: 'real-estate-registry' },
      { id: 'fees', type: 'action', titleAr: 'دفع رسوم التسجيل', titleEn: 'Pay Registration Fees', status: 'not_started' },
      { id: 'completion', type: 'completion', titleAr: 'اكتمال نقل الملكية', titleEn: 'Transfer Complete', status: 'not_started' },
    ],
    edges: [
      { id: 'e1', from: 'start', to: 'docs' },
      { id: 'e2', from: 'docs', to: 'notary' },
      { id: 'e3', from: 'notary', to: 'contract' },
      { id: 'e4', from: 'contract', to: 'risk_check' },
      { id: 'e5', from: 'risk_check', to: 'registry', labelAr: 'بعد التحقق' },
      { id: 'e6', from: 'registry', to: 'fees' },
      { id: 'e7', from: 'fees', to: 'completion' },
    ],
  },

  'power-of-attorney': {
    procedureSlug: 'power-of-attorney',
    titleAr: 'وكالة قانونية',
    titleEn: 'Power of Attorney',
    country: 'lebanon',
    version: '1.0',
    verificationStatus: 'partially_verified',
    estimatedDurationAr: '1-3 أيام',
    estimatedDurationEn: '1-3 days',
    nodes: [
      { id: 'start', type: 'start', titleAr: 'بداية إجراء الوكالة', titleEn: 'Start POA', status: 'current' },
      { id: 'scope', type: 'question', titleAr: 'تحديد صلاحيات الوكالة', titleEn: 'Define POA Scope', descriptionAr: 'هل هي وكالة بيع؟ متابعة معاملة؟ قبض؟', status: 'not_started' },
      { id: 'draft', type: 'draft', titleAr: 'إعداد نص الوكالة', titleEn: 'Draft POA Text', descriptionAr: 'يُنصح بصياغتها من محامٍ', riskLevel: 'medium', status: 'not_started' },
      { id: 'risk', type: 'risk', titleAr: 'مراجعة الصلاحيات', titleEn: 'Review Scope Risk', descriptionAr: 'وكالة مفتوحة تحمل مخاطر عالية', status: 'not_started' },
      { id: 'notary', type: 'authority', titleAr: 'التوقيع أمام الكاتب العدل', titleEn: 'Sign Before Notary', relatedAuthority: 'notary-public', status: 'not_started' },
      { id: 'abroad', type: 'question', titleAr: 'هل الوكيل خارج لبنان؟', titleEn: 'Attorney Abroad?', status: 'not_started' },
      { id: 'apostille', type: 'action', titleAr: 'تصديق وزارة الخارجية', titleEn: 'Foreign Affairs Apostille', status: 'not_started' },
      { id: 'completion', type: 'completion', titleAr: 'الوكالة جاهزة', titleEn: 'POA Ready', status: 'not_started' },
    ],
    edges: [
      { id: 'e1', from: 'start', to: 'scope' },
      { id: 'e2', from: 'scope', to: 'draft' },
      { id: 'e3', from: 'draft', to: 'risk' },
      { id: 'e4', from: 'risk', to: 'notary', labelAr: 'بعد المراجعة' },
      { id: 'e5', from: 'notary', to: 'abroad' },
      { id: 'e6', from: 'abroad', to: 'apostille', labelAr: 'نعم' },
      { id: 'e7', from: 'abroad', to: 'completion', labelAr: 'لا' },
      { id: 'e8', from: 'apostille', to: 'completion' },
    ],
  },

  'inheritance': {
    procedureSlug: 'inheritance',
    titleAr: 'حصر الإرث',
    titleEn: 'Inheritance',
    country: 'lebanon',
    version: '1.0',
    verificationStatus: 'partially_verified',
    estimatedDurationAr: '2-6 أشهر',
    estimatedDurationEn: '2-6 months',
    nodes: [
      { id: 'start', type: 'start', titleAr: 'بداية إجراء الإرث', titleEn: 'Start Inheritance', status: 'current' },
      { id: 'docs', type: 'document', titleAr: 'جمع وثائق الورثة', titleEn: 'Gather Heir Documents', descriptionAr: 'قيد عائلي، وثيقة وفاة المورّث، هويات الورثة', requiredDocuments: ['قيد عائلي', 'وثيقة وفاة', 'هويات الورثة'], status: 'not_started' },
      { id: 'q_property', type: 'question', titleAr: 'هل هناك عقارات في التركة؟', titleEn: 'Are there properties?', status: 'not_started' },
      { id: 'court', type: 'authority', titleAr: 'مراجعة المحكمة الشرعية أو المدنية', titleEn: 'Visit Court', relatedAuthority: 'ministry-of-justice', status: 'not_started' },
      { id: 'request', type: 'action', titleAr: 'طلب قرار حصر الإرث', titleEn: 'Request Inheritance Decree', status: 'not_started', riskLevel: 'medium' },
      { id: 'review', type: 'human_review', titleAr: 'مراجعة قانونية للقرار', titleEn: 'Legal Review of Decree', descriptionAr: 'يُنصح بمراجعة محامٍ للتأكد من صحة القرار', status: 'not_started' },
      { id: 'registry', type: 'authority', titleAr: 'تسجيل العقارات في السجل العقاري', titleEn: 'Register Properties', relatedAuthority: 'real-estate-registry', status: 'not_started' },
      { id: 'completion', type: 'completion', titleAr: 'اكتمال حصر الإرث', titleEn: 'Inheritance Complete', status: 'not_started' },
    ],
    edges: [
      { id: 'e1', from: 'start', to: 'docs' },
      { id: 'e2', from: 'docs', to: 'q_property' },
      { id: 'e3', from: 'q_property', to: 'court', labelAr: 'نعم — عقارات موجودة' },
      { id: 'e4', from: 'q_property', to: 'request', labelAr: 'لا عقارات' },
      { id: 'e5', from: 'court', to: 'request' },
      { id: 'e6', from: 'request', to: 'review' },
      { id: 'e7', from: 'review', to: 'registry', labelAr: 'بعد المراجعة' },
      { id: 'e8', from: 'registry', to: 'completion' },
    ],
  },

  'company-formation': {
    procedureSlug: 'company-formation',
    titleAr: 'تأسيس شركة',
    titleEn: 'Company Formation',
    country: 'lebanon',
    version: '1.0',
    verificationStatus: 'partially_verified',
    estimatedDurationAr: '2-4 أسابيع',
    estimatedDurationEn: '2-4 weeks',
    nodes: [
      { id: 'start', type: 'start', titleAr: 'بداية تأسيس الشركة', titleEn: 'Start Company Formation', status: 'current' },
      { id: 'legal_form', type: 'question', titleAr: 'اختيار الشكل القانوني', titleEn: 'Choose Legal Form', descriptionAr: 'ش.م.م، ش.م.أ، شركة تضامن، أو شركة فردية', status: 'not_started' },
      { id: 'contract', type: 'draft', titleAr: 'تجهيز العقد التأسيسي', titleEn: 'Prepare Founding Contract', descriptionAr: 'يجب صياغته من محامٍ أو كاتب عدل', status: 'not_started', riskLevel: 'medium' },
      { id: 'mof', type: 'authority', titleAr: 'التسجيل في وزارة المالية', titleEn: 'Register with Ministry of Finance', relatedAuthority: 'ministry-of-finance', status: 'not_started' },
      { id: 'bank', type: 'action', titleAr: 'فتح حساب مصرفي', titleEn: 'Open Bank Account', status: 'not_started' },
      { id: 'commercial', type: 'authority', titleAr: 'التسجيل في السجل التجاري', titleEn: 'Register in Commercial Registry', relatedAuthority: 'commercial-registry', status: 'not_started' },
      { id: 'publish', type: 'action', titleAr: 'النشر في الجريدة الرسمية', titleEn: 'Publish in Official Gazette', status: 'not_started' },
      { id: 'completion', type: 'completion', titleAr: 'الشركة مُسجّلة رسمياً', titleEn: 'Company Registered', status: 'not_started' },
    ],
    edges: [
      { id: 'e1', from: 'start', to: 'legal_form' },
      { id: 'e2', from: 'legal_form', to: 'contract' },
      { id: 'e3', from: 'contract', to: 'mof' },
      { id: 'e4', from: 'mof', to: 'bank' },
      { id: 'e5', from: 'bank', to: 'commercial' },
      { id: 'e6', from: 'commercial', to: 'publish' },
      { id: 'e7', from: 'publish', to: 'completion' },
    ],
  },

  'civil-record': {
    procedureSlug: 'civil-record',
    titleAr: 'استخراج وثيقة نفوس',
    titleEn: 'Civil Record',
    country: 'lebanon',
    version: '1.0',
    verificationStatus: 'partially_verified',
    estimatedDurationAr: '1-3 أيام',
    estimatedDurationEn: '1-3 days',
    nodes: [
      { id: 'start', type: 'start', titleAr: 'بداية استخراج وثيقة نفوس', titleEn: 'Start Civil Record', status: 'current' },
      { id: 'type', type: 'question', titleAr: 'تحديد نوع الوثيقة', titleEn: 'Determine Document Type', descriptionAr: 'قيد عائلي، شهادة ميلاد، وثيقة فردية', status: 'not_started' },
      { id: 'civil', type: 'authority', titleAr: 'مراجعة دائرة النفوس', titleEn: 'Visit Civil Registry', relatedAuthority: 'civil-registry', status: 'not_started' },
      { id: 'submit', type: 'action', titleAr: 'تقديم الطلب والهوية', titleEn: 'Submit Request', requiredDocuments: ['هوية شخصية', 'وثيقة تعريف'], status: 'not_started' },
      { id: 'fees', type: 'action', titleAr: 'دفع رسم الاستخراج', titleEn: 'Pay Extraction Fee', status: 'not_started' },
      { id: 'completion', type: 'completion', titleAr: 'استلام الوثيقة', titleEn: 'Receive Document', status: 'not_started' },
    ],
    edges: [
      { id: 'e1', from: 'start', to: 'type' },
      { id: 'e2', from: 'type', to: 'civil' },
      { id: 'e3', from: 'civil', to: 'submit' },
      { id: 'e4', from: 'submit', to: 'fees' },
      { id: 'e5', from: 'fees', to: 'completion' },
    ],
  },

  'document-certification': {
    procedureSlug: 'document-certification',
    titleAr: 'تصديق مستند',
    titleEn: 'Document Certification',
    country: 'lebanon',
    version: '1.0',
    verificationStatus: 'partially_verified',
    estimatedDurationAr: '1-5 أيام',
    estimatedDurationEn: '1-5 days',
    nodes: [
      { id: 'start', type: 'start', titleAr: 'بداية إجراء التصديق', titleEn: 'Start Certification', status: 'current' },
      { id: 'type', type: 'question', titleAr: 'تحديد نوع التصديق المطلوب', titleEn: 'Determine Certification Type', descriptionAr: 'تصديق محلي، أم للخارج (أبوستيل)؟', status: 'not_started' },
      { id: 'notarize', type: 'authority', titleAr: 'توثيق المستند لدى كاتب العدل', titleEn: 'Notarize Document', relatedAuthority: 'notary-public', status: 'not_started' },
      { id: 'q_abroad', type: 'question', titleAr: 'هل المستند مطلوب خارج لبنان؟', titleEn: 'Required outside Lebanon?', status: 'not_started' },
      { id: 'foreign_affairs', type: 'authority', titleAr: 'تصديق وزارة الخارجية', titleEn: 'Foreign Affairs Certification', relatedAuthority: 'ministry-of-foreign-affairs', status: 'not_started' },
      { id: 'translate', type: 'action', titleAr: 'ترجمة رسمية إذا مطلوب', titleEn: 'Official Translation if Required', status: 'not_started', riskLevel: 'low' },
      { id: 'completion', type: 'completion', titleAr: 'المستند مصدَّق وجاهز', titleEn: 'Document Certified', status: 'not_started' },
    ],
    edges: [
      { id: 'e1', from: 'start', to: 'type' },
      { id: 'e2', from: 'type', to: 'notarize' },
      { id: 'e3', from: 'notarize', to: 'q_abroad' },
      { id: 'e4', from: 'q_abroad', to: 'foreign_affairs', labelAr: 'نعم' },
      { id: 'e5', from: 'q_abroad', to: 'completion', labelAr: 'لا' },
      { id: 'e6', from: 'foreign_affairs', to: 'translate' },
      { id: 'e7', from: 'translate', to: 'completion' },
    ],
  },
}
