// دليلك — خرائط الرحلات الحياتية
// كل رحلة = حدث حياتي يجمع عدة إجراءات حكومية مترابطة في تسلسل منطقي

export interface JourneyStep {
  titleAr: string
  titleEn: string
  authorityAr: string
  authorityEn: string
  estAr: string       // وقت التقدير (عربي)
  estEn: string       // وقت التقدير (إنجليزي)
  feesAr: string
  feesEn: string
  promptAr: string    // prompt للـ AI
  promptEn: string
  optional?: boolean
  parallel?: boolean  // يمكن إنجازه بالتوازي مع الخطوة السابقة
}

export interface LifeJourney {
  slug: string
  emoji: string
  titleAr: string
  titleEn: string
  subtitleAr: string
  subtitleEn: string
  descAr: string
  descEn: string
  totalEstAr: string   // الوقت الإجمالي التقديري
  totalEstEn: string
  totalFeesAr: string
  totalFeesEn: string
  steps: JourneyStep[]
  tipsAr: string[]
  tipsEn: string[]
}

export const LIFE_JOURNEYS: LifeJourney[] = [
  {
    slug: 'newborn',
    emoji: '👶',
    titleAr: 'وُلد مولود',
    titleEn: 'New Baby',
    subtitleAr: '٤ إجراءات — ٣٠ يوماً',
    subtitleEn: '4 procedures — 30 days',
    descAr: 'كل ما تحتاجه بعد الولادة: من تسجيل المولود في السجل المدني إلى استخراج وثائقه الرسمية.',
    descEn: 'Everything needed after birth: from civil registry registration to obtaining official documents.',
    totalEstAr: '٣–٤ أسابيع',
    totalEstEn: '3–4 weeks',
    totalFeesAr: 'بدون رسوم تقريباً',
    totalFeesEn: 'Mostly free',
    steps: [
      {
        titleAr: 'تسجيل الولادة في السجل المدني',
        titleEn: 'Birth Registration – Civil Registry',
        authorityAr: 'وزارة الداخلية — السجل المدني',
        authorityEn: 'Ministry of Interior — Civil Registry',
        estAr: '٣–١٠ أيام',
        estEn: '3–10 days',
        feesAr: 'مجاني',
        feesEn: 'Free',
        promptAr: 'كيف أسجّل مولوداً جديداً في السجل المدني في لبنان؟ ما هي الوثائق المطلوبة والمهلة القانونية؟',
        promptEn: 'How do I register a newborn in the Lebanese civil registry? What documents are required and what is the legal deadline?',
      },
      {
        titleAr: 'استخراج شهادة الميلاد',
        titleEn: 'Obtain Birth Certificate',
        authorityAr: 'وزارة الداخلية — السجل المدني',
        authorityEn: 'Ministry of Interior — Civil Registry',
        estAr: '١–٣ أيام',
        estEn: '1–3 days',
        feesAr: 'مجاني',
        feesEn: 'Free',
        promptAr: 'كيف أستخرج شهادة ميلاد لمولود جديد في لبنان؟',
        promptEn: 'How do I get a birth certificate for a newborn in Lebanon?',
      },
      {
        titleAr: 'استخراج إخراج قيد عائلي محدَّث',
        titleEn: 'Updated Family Registry Extract',
        authorityAr: 'وزارة الداخلية — السجل المدني',
        authorityEn: 'Ministry of Interior — Civil Registry',
        estAr: '١–٥ أيام',
        estEn: '1–5 days',
        feesAr: 'مجاني',
        feesEn: 'Free',
        promptAr: 'كيف أستخرج إخراج قيد عائلي محدّث بعد إضافة مولود في لبنان؟',
        promptEn: 'How do I get an updated family registry extract after adding a newborn in Lebanon?',
        parallel: true,
      },
      {
        titleAr: 'تسجيل في الضمان الاجتماعي (إن ينطبق)',
        titleEn: 'Social Security Registration (if applicable)',
        authorityAr: 'الصندوق الوطني للضمان الاجتماعي',
        authorityEn: 'National Social Security Fund',
        estAr: '٧–١٤ يوماً',
        estEn: '7–14 days',
        feesAr: 'مجاني',
        feesEn: 'Free',
        promptAr: 'كيف أضيف مولوداً جديداً إلى تغطية الضمان الاجتماعي في لبنان؟',
        promptEn: 'How do I add a newborn to social security coverage in Lebanon?',
        optional: true,
      },
    ],
    tipsAr: [
      'المهلة القانونية لتسجيل الولادة هي ٣٠ يوماً من تاريخ الولادة — تجاوزها يستلزم إجراءات قضائية مكلفة',
      'شهادة الأم من المستشفى ضرورية — احتفظ بها فور الخروج من المستشفى',
      'يمكن إنجاز التسجيل في مختار المنطقة أو مباشرة في السجل المدني',
    ],
    tipsEn: [
      'The legal deadline for birth registration is 30 days — missing it requires costly court procedures',
      "Keep the hospital birth certificate — it's required for civil registry registration",
      'Registration can be done at the local mukhtar or directly at the civil registry office',
    ],
  },
  {
    slug: 'marriage',
    emoji: '💍',
    titleAr: 'أنا أتزوج',
    titleEn: 'Getting Married',
    subtitleAr: '٥ إجراءات — ٢–٦ أسابيع',
    subtitleEn: '5 procedures — 2–6 weeks',
    descAr: 'من اختيار نوع عقد الزواج إلى استخراج وثائق الأحوال الشخصية المحدّثة.',
    descEn: 'From choosing the marriage contract type to obtaining updated personal status documents.',
    totalEstAr: '٢–٦ أسابيع',
    totalEstEn: '2–6 weeks',
    totalFeesAr: 'تتفاوت حسب طريقة الزواج',
    totalFeesEn: 'Varies by marriage type',
    steps: [
      {
        titleAr: 'استخراج إخراج قيد فردي حديث',
        titleEn: 'Current Civil Registry Extract',
        authorityAr: 'السجل المدني',
        authorityEn: 'Civil Registry',
        estAr: '١–٣ أيام',
        estEn: '1–3 days',
        feesAr: 'مجاني',
        feesEn: 'Free',
        promptAr: 'كيف أستخرج إخراج قيد فردي من السجل المدني في لبنان؟',
        promptEn: 'How do I get a civil registry extract in Lebanon?',
      },
      {
        titleAr: 'شهادة عدم الزواج (عزوبية)',
        titleEn: 'Certificate of Celibacy',
        authorityAr: 'وزارة الداخلية / الجهة الدينية المختصة',
        authorityEn: 'Ministry of Interior / Religious Authority',
        estAr: '٣–٧ أيام',
        estEn: '3–7 days',
        feesAr: 'رمزي',
        feesEn: 'Nominal',
        promptAr: 'كيف أستخرج شهادة عزوبية أو عدم زواج في لبنان؟',
        promptEn: 'How do I get a certificate of celibacy in Lebanon?',
      },
      {
        titleAr: 'عقد الزواج الديني أو المدني',
        titleEn: 'Religious or Civil Marriage Contract',
        authorityAr: 'الجهة الدينية المختصة أو كاتب العدل',
        authorityEn: 'Religious Authority or Notary Public',
        estAr: '١–٣ أسابيع',
        estEn: '1–3 weeks',
        feesAr: 'يتوقف على الطائفة والوثائق',
        feesEn: 'Varies by denomination',
        promptAr: 'كيف أُبرم عقد زواج في لبنان؟ ما الفرق بين الزواج الديني والمدني؟',
        promptEn: 'How do I sign a marriage contract in Lebanon? What is the difference between religious and civil marriage?',
      },
      {
        titleAr: 'تسجيل عقد الزواج في السجل المدني',
        titleEn: 'Register Marriage in Civil Registry',
        authorityAr: 'وزارة الداخلية — السجل المدني',
        authorityEn: 'Ministry of Interior — Civil Registry',
        estAr: '١–٢ أسابيع',
        estEn: '1–2 weeks',
        feesAr: 'مجاني',
        feesEn: 'Free',
        promptAr: 'كيف أسجّل عقد زواج في السجل المدني اللبناني؟',
        promptEn: 'How do I register a marriage contract in the Lebanese civil registry?',
      },
      {
        titleAr: 'استخراج إخراج قيد عائلي مشترك',
        titleEn: 'Joint Family Registry Extract',
        authorityAr: 'وزارة الداخلية — السجل المدني',
        authorityEn: 'Ministry of Interior — Civil Registry',
        estAr: '١–٣ أيام',
        estEn: '1–3 days',
        feesAr: 'مجاني',
        feesEn: 'Free',
        promptAr: 'كيف أستخرج إخراج قيد عائلي مشترك بعد الزواج في لبنان؟',
        promptEn: 'How do I get a joint family registry extract after getting married in Lebanon?',
      },
    ],
    tipsAr: [
      'في لبنان لا زواج مدني — بديله إما الزواج الديني أو السفر لقبرص للزواج المدني',
      'تأكّد من صلاحية كل وثائقك — إخراج القيد يصبح "منتهياً" بعد ٣ أشهر في كثير من الدوائر',
      'إن كان أحد الطرفين أجنبياً تحتاج وثائق إضافية من سفارة بلده',
    ],
    tipsEn: [
      'Lebanon has no civil marriage — alternatives are religious marriage or traveling to Cyprus',
      'Verify all documents are current — registry extracts expire after 3 months in many offices',
      "If one party is a foreigner, additional documents from their country's embassy are required",
    ],
  },
  {
    slug: 'start-business',
    emoji: '🏢',
    titleAr: 'أريد فتح شركة',
    titleEn: 'Starting a Business',
    subtitleAr: '٧ إجراءات — ٣–٨ أسابيع',
    subtitleEn: '7 procedures — 3–8 weeks',
    descAr: 'من اختيار الشكل القانوني للشركة إلى الحصول على الترخيص التجاري وتسجيل الموظفين.',
    descEn: 'From choosing your legal structure to obtaining a trade license and registering employees.',
    totalEstAr: '٣–٨ أسابيع',
    totalEstEn: '3–8 weeks',
    totalFeesAr: '١٠٠–٥٠٠ دولار (تقريباً)',
    totalFeesEn: '$100–$500 (approx.)',
    steps: [
      {
        titleAr: 'اختيار الشكل القانوني وتحضير العقد التأسيسي',
        titleEn: 'Choose Legal Structure & Draft Articles',
        authorityAr: 'كاتب العدل',
        authorityEn: 'Notary Public',
        estAr: '٣–٧ أيام',
        estEn: '3–7 days',
        feesAr: 'أتعاب كاتب العدل',
        feesEn: 'Notary fees',
        promptAr: 'ما هي أنواع الشركات في لبنان وكيف أختار الشكل المناسب لمشروعي؟',
        promptEn: 'What types of companies exist in Lebanon and how do I choose the right structure for my business?',
      },
      {
        titleAr: 'التسجيل في محكمة التجارة',
        titleEn: 'Registration at Commercial Court',
        authorityAr: 'محكمة التجارة',
        authorityEn: 'Commercial Court',
        estAr: '٣–١٠ أيام',
        estEn: '3–10 days',
        feesAr: 'حسب رأس المال',
        feesEn: 'Based on capital',
        promptAr: 'كيف أسجّل شركة في محكمة التجارة في لبنان؟ ما هي الوثائق المطلوبة؟',
        promptEn: 'How do I register a company at the commercial court in Lebanon? What documents are required?',
      },
      {
        titleAr: 'التسجيل في وزارة الاقتصاد والتجارة',
        titleEn: 'Register at Ministry of Economy',
        authorityAr: 'وزارة الاقتصاد والتجارة',
        authorityEn: 'Ministry of Economy & Trade',
        estAr: '٣–٧ أيام',
        estEn: '3–7 days',
        feesAr: 'رسوم بسيطة',
        feesEn: 'Minor fees',
        promptAr: 'كيف أسجّل شركتي في وزارة الاقتصاد والتجارة في لبنان؟',
        promptEn: 'How do I register my company with the Ministry of Economy and Trade in Lebanon?',
      },
      {
        titleAr: 'الحصول على الرقم المالي',
        titleEn: 'Obtain Tax Registration Number',
        authorityAr: 'وزارة المالية',
        authorityEn: 'Ministry of Finance',
        estAr: '٣–٥ أيام',
        estEn: '3–5 days',
        feesAr: 'مجاني',
        feesEn: 'Free',
        promptAr: 'كيف أحصل على رقم مالي لشركتي في لبنان من وزارة المالية؟',
        promptEn: 'How do I get a tax identification number for my company from the Ministry of Finance in Lebanon?',
      },
      {
        titleAr: 'الاشتراك في الضمان الاجتماعي',
        titleEn: 'Social Security Enrollment',
        authorityAr: 'الصندوق الوطني للضمان الاجتماعي',
        authorityEn: 'National Social Security Fund',
        estAr: '٣–٧ أيام',
        estEn: '3–7 days',
        feesAr: 'مجاني (+ اشتراكات دورية)',
        feesEn: 'Free (+ recurring contributions)',
        promptAr: 'كيف أسجّل شركتي في الصندوق الوطني للضمان الاجتماعي في لبنان؟',
        promptEn: 'How do I register my company with the National Social Security Fund in Lebanon?',
      },
      {
        titleAr: 'الحصول على رخصة البلدية',
        titleEn: 'Municipal License (Ruhsat)',
        authorityAr: 'البلدية المختصة',
        authorityEn: 'Local Municipality',
        estAr: '١–٤ أسابيع',
        estEn: '1–4 weeks',
        feesAr: 'حسب نوع النشاط',
        feesEn: 'Varies by activity',
        promptAr: 'كيف أحصل على رخصة مزاولة المهنة من البلدية في لبنان؟',
        promptEn: 'How do I get a business license (ruhsat) from the municipality in Lebanon?',
      },
      {
        titleAr: 'فتح حساب مصرفي تجاري',
        titleEn: 'Open Business Bank Account',
        authorityAr: 'أحد البنوك اللبنانية',
        authorityEn: 'Lebanese Bank',
        estAr: '٣–٧ أيام',
        estEn: '3–7 days',
        feesAr: 'يتوقف على البنك',
        feesEn: 'Varies by bank',
        promptAr: 'كيف أفتح حساباً مصرفياً تجارياً لشركة في لبنان؟',
        promptEn: 'How do I open a business bank account for a company in Lebanon?',
      },
    ],
    tipsAr: [
      'شركة المحاصة (Société en participation) لا تحتاج تسجيلاً ولكنها لا تتمتع بشخصية قانونية مستقلة',
      'احتفظ بنسخ إضافية من كل وثيقة موثّقة — ستحتاجها لاحقاً في كل خطوة',
      'الرقم المالي ضروري قبل أي فاتورة أو عقد تجاري',
    ],
    tipsEn: [
      'A société en participation requires no registration but has no separate legal personality',
      'Keep extra certified copies of every notarized document — you will need them at each step',
      'A tax number is required before any invoice or commercial contract',
    ],
  },
  {
    slug: 'passport-travel',
    emoji: '✈️',
    titleAr: 'أريد السفر أو الهجرة',
    titleEn: 'Traveling or Emigrating',
    subtitleAr: '٤–٦ إجراءات — ٢–٦ أسابيع',
    subtitleEn: '4–6 procedures — 2–6 weeks',
    descAr: 'استخراج جواز السفر وتوثيق وثائقك قبل مغادرة لبنان أو طلب الإقامة في الخارج.',
    descEn: 'Getting your passport and certifying your documents before leaving Lebanon or applying for foreign residency.',
    totalEstAr: '٢–٦ أسابيع',
    totalEstEn: '2–6 weeks',
    totalFeesAr: '٥٠–١٥٠ دولار (تقريباً)',
    totalFeesEn: '$50–$150 (approx.)',
    steps: [
      {
        titleAr: 'استخراج أو تجديد جواز السفر',
        titleEn: 'Get or Renew Passport',
        authorityAr: 'المديرية العامة للأمن العام',
        authorityEn: 'General Directorate of General Security',
        estAr: '١–٤ أسابيع',
        estEn: '1–4 weeks',
        feesAr: 'حسب نوع الجواز والأولوية',
        feesEn: 'Varies by type and priority',
        promptAr: 'كيف أستخرج أو أجدد جواز السفر اللبناني؟ ما هي الوثائق المطلوبة والرسوم؟',
        promptEn: 'How do I get or renew a Lebanese passport? What are the required documents and fees?',
      },
      {
        titleAr: 'استخراج إخراج قيد فردي للسفر',
        titleEn: 'Civil Registry Extract for Travel',
        authorityAr: 'وزارة الداخلية — السجل المدني',
        authorityEn: 'Ministry of Interior — Civil Registry',
        estAr: '١–٣ أيام',
        estEn: '1–3 days',
        feesAr: 'مجاني',
        feesEn: 'Free',
        promptAr: 'كيف أستخرج إخراج قيد فردي للسفر أو التقديم على تأشيرة؟',
        promptEn: 'How do I get a civil registry extract for travel or visa applications?',
      },
      {
        titleAr: 'توثيق الوثائق بالأبوستيل أو بالتصديق الدبلوماسي',
        titleEn: 'Apostille or Diplomatic Certification',
        authorityAr: 'وزارة الخارجية / وزارة العدل',
        authorityEn: 'Ministry of Foreign Affairs / Ministry of Justice',
        estAr: '٣–٧ أيام',
        estEn: '3–7 days',
        feesAr: 'رسوم بسيطة لكل وثيقة',
        feesEn: 'Small fee per document',
        promptAr: 'كيف أوثّق وثائقي بختم الأبوستيل في لبنان؟ ما هو الفرق بين الأبوستيل والتصديق الدبلوماسي؟',
        promptEn: 'How do I get an apostille stamp in Lebanon? What is the difference between apostille and diplomatic certification?',
      },
      {
        titleAr: 'وكالة رسمية (إن احتجت وكيلاً في لبنان)',
        titleEn: 'Power of Attorney (if leaving a proxy)',
        authorityAr: 'كاتب العدل',
        authorityEn: 'Notary Public',
        estAr: '١–٣ أيام',
        estEn: '1–3 days',
        feesAr: 'أتعاب كاتب العدل',
        feesEn: 'Notary fees',
        promptAr: 'كيف أُعطي وكالة رسمية لشخص ما في لبنان قبل سفري؟',
        promptEn: 'How do I grant a power of attorney to someone in Lebanon before I travel?',
        optional: true,
      },
      {
        titleAr: 'إخلاء الذمة من الجيش (للذكور)',
        titleEn: 'Military Clearance (for males)',
        authorityAr: 'وزارة الدفاع — مديرية التجنيد',
        authorityEn: 'Ministry of National Defence',
        estAr: '٣–١٤ يوماً',
        estEn: '3–14 days',
        feesAr: 'مجاني',
        feesEn: 'Free',
        promptAr: 'كيف أحصل على إخلاء ذمة من الجيش اللبناني قبل السفر للخارج؟',
        promptEn: 'How do I get a military clearance from the Lebanese army before traveling abroad?',
        optional: true,
      },
    ],
    tipsAr: [
      'تقدّم بطلب جواز السفر مبكراً — قد يستغرق ٤ أسابيع في أوقات الذروة',
      'اطلب نسختين على الأقل من كل وثيقة موثّقة — ستحتاجها في كل سفارة',
      'الأبوستيل مقبول في دول اتفاقية لاهاي (أوروبا، أمريكا)، والتصديق الدبلوماسي للدول الأخرى',
    ],
    tipsEn: [
      'Apply for your passport early — it can take up to 4 weeks during peak periods',
      'Request at least 2 copies of each certified document — embassies will keep originals',
      'Apostille is accepted in Hague Convention countries; diplomatic certification for others',
    ],
  },
  {
    slug: 'property-purchase',
    emoji: '🏠',
    titleAr: 'أريد شراء عقار',
    titleEn: 'Buying Property',
    subtitleAr: '٦ إجراءات — ٤–١٢ أسبوعاً',
    subtitleEn: '6 procedures — 4–12 weeks',
    descAr: 'من التحقق من ملكية العقار إلى تسجيل العقد في دائرة الشهر العقاري.',
    descEn: 'From verifying property ownership to registering the contract at the land registry.',
    totalEstAr: '٤–١٢ أسبوعاً',
    totalEstEn: '4–12 weeks',
    totalFeesAr: '٦–٨٪ من قيمة العقار',
    totalFeesEn: '6–8% of property value',
    steps: [
      {
        titleAr: 'التحقق من صحيفة العقار في الشهر العقاري',
        titleEn: 'Verify Title Deed at Land Registry',
        authorityAr: 'دائرة الشهر العقاري',
        authorityEn: 'Land Registry',
        estAr: '١–٣ أيام',
        estEn: '1–3 days',
        feesAr: 'رسوم بسيطة',
        feesEn: 'Minor fees',
        promptAr: 'كيف أتحقق من صحيفة عقار أو سند ملكية في لبنان قبل الشراء؟',
        promptEn: 'How do I verify a property title deed in Lebanon before purchase?',
      },
      {
        titleAr: 'عقد البيع الأوّلي (أومبرومي) عند كاتب العدل',
        titleEn: 'Preliminary Sale Contract (Compromis)',
        authorityAr: 'كاتب العدل',
        authorityEn: 'Notary Public',
        estAr: '٣–٧ أيام',
        estEn: '3–7 days',
        feesAr: 'أتعاب كاتب العدل',
        feesEn: 'Notary fees',
        promptAr: 'ما هو عقد البيع الأومبرومي في لبنان وكيف يُبرم عند كاتب العدل؟',
        promptEn: 'What is a preliminary sale contract (compromis) in Lebanon and how is it signed?',
      },
      {
        titleAr: 'الحصول على إفادة تسوية ضريبية',
        titleEn: 'Tax Clearance Certificate',
        authorityAr: 'وزارة المالية',
        authorityEn: 'Ministry of Finance',
        estAr: '١–٣ أسابيع',
        estEn: '1–3 weeks',
        feesAr: 'مجاني',
        feesEn: 'Free',
        promptAr: 'كيف أحصل على إفادة براءة ذمة ضريبية لعقار في لبنان؟',
        promptEn: 'How do I get a property tax clearance certificate in Lebanon?',
      },
      {
        titleAr: 'عقد البيع النهائي وتوثيقه',
        titleEn: 'Final Notarized Sale Contract',
        authorityAr: 'كاتب العدل',
        authorityEn: 'Notary Public',
        estAr: '١–٣ أيام',
        estEn: '1–3 days',
        feesAr: 'الرسوم والضريبة على العقارات',
        feesEn: 'Registration fees + property tax',
        promptAr: 'كيف يُبرم عقد البيع النهائي لعقار في لبنان؟ ما هي الرسوم والضرائب؟',
        promptEn: 'How is the final property sale contract signed in Lebanon? What are the fees and taxes?',
      },
      {
        titleAr: 'نقل الملكية في الشهر العقاري',
        titleEn: 'Title Transfer at Land Registry',
        authorityAr: 'دائرة الشهر العقاري',
        authorityEn: 'Land Registry',
        estAr: '١–٤ أسابيع',
        estEn: '1–4 weeks',
        feesAr: 'رسوم النقل (٥٪ من قيمة العقار)',
        feesEn: 'Transfer fee (5% of property value)',
        promptAr: 'كيف أنقل ملكية عقار في السجل العقاري اللبناني؟ ما هي رسوم نقل الملكية؟',
        promptEn: 'How do I transfer property ownership in the Lebanese land registry? What are the transfer fees?',
      },
      {
        titleAr: 'الحصول على سند الملكية الجديد',
        titleEn: 'Receive New Title Deed',
        authorityAr: 'دائرة الشهر العقاري',
        authorityEn: 'Land Registry',
        estAr: '١–٤ أسابيع',
        estEn: '1–4 weeks',
        feesAr: 'رسوم بسيطة',
        feesEn: 'Minor fees',
        promptAr: 'كيف أستلم سند الملكية الجديد من دائرة الشهر العقاري في لبنان؟',
        promptEn: 'How do I receive the new title deed from the Lebanese land registry?',
      },
    ],
    tipsAr: [
      'تأكّد من أن العقار خالٍ من الرهون والحجوزات قبل أي دفعة — اطلب كشف الصحيفة من الشهر العقاري',
      'رسوم التحويل والضرائب قد تصل إلى ٦–٨٪ من قيمة العقار — احسبها في ميزانيتك',
      'الأجانب ملزمون بالحصول على إذن مجلس الوزراء لشراء عقارات تزيد مساحتها عن ٣٠٠٠ م²',
    ],
    tipsEn: [
      'Verify the property is free of mortgages and liens before any payment — request a title search',
      'Transfer fees and taxes can reach 6–8% of the property value — budget for them',
      'Foreigners must obtain Council of Ministers approval to purchase property over 3,000 m²',
    ],
  },
  {
    slug: 'death-inheritance',
    emoji: '🕊️',
    titleAr: 'وفاة وإرث',
    titleEn: 'Death & Inheritance',
    subtitleAr: '٦ إجراءات — ٤–١٢ أسبوعاً',
    subtitleEn: '6 procedures — 4–12 weeks',
    descAr: 'من تسجيل الوفاة إلى انتقال الملكية والحقوق القانونية للورثة.',
    descEn: 'From registering the death to transferring property and legal rights to the heirs.',
    totalEstAr: '٤–١٢ أسبوعاً',
    totalEstEn: '4–12 weeks',
    totalFeesAr: 'يتوقف على التركة',
    totalFeesEn: 'Depends on estate',
    steps: [
      {
        titleAr: 'تسجيل الوفاة في السجل المدني',
        titleEn: 'Death Registration – Civil Registry',
        authorityAr: 'وزارة الداخلية — السجل المدني',
        authorityEn: 'Ministry of Interior — Civil Registry',
        estAr: '١–٣ أيام',
        estEn: '1–3 days',
        feesAr: 'مجاني',
        feesEn: 'Free',
        promptAr: 'كيف أسجّل وفاة شخص في السجل المدني اللبناني؟ ما هي الوثائق المطلوبة؟',
        promptEn: 'How do I register a death in the Lebanese civil registry? What documents are needed?',
      },
      {
        titleAr: 'استخراج شهادة الوفاة',
        titleEn: 'Obtain Death Certificate',
        authorityAr: 'وزارة الداخلية — السجل المدني',
        authorityEn: 'Ministry of Interior — Civil Registry',
        estAr: '١–٣ أيام',
        estEn: '1–3 days',
        feesAr: 'مجاني',
        feesEn: 'Free',
        promptAr: 'كيف أستخرج شهادة وفاة من السجل المدني في لبنان؟',
        promptEn: 'How do I obtain a death certificate from the Lebanese civil registry?',
      },
      {
        titleAr: 'حصر الإرث عند القضاء المختص',
        titleEn: 'Succession Certificate from Court',
        authorityAr: 'المحكمة الشرعية أو المدنية المختصة',
        authorityEn: 'Religious or Civil Court',
        estAr: '٢–٨ أسابيع',
        estEn: '2–8 weeks',
        feesAr: 'رسوم قضائية',
        feesEn: 'Court fees',
        promptAr: 'كيف أستخرج حجة حصر إرث في لبنان؟ أي محكمة مختصة؟',
        promptEn: 'How do I get a succession certificate in Lebanon? Which court is competent?',
      },
      {
        titleAr: 'تصفية الحسابات المصرفية للمتوفى',
        titleEn: 'Settle Deceased\'s Bank Accounts',
        authorityAr: 'البنك المعني + المصرف المركزي',
        authorityEn: 'Relevant Bank + Central Bank',
        estAr: '٢–١٢ أسبوعاً',
        estEn: '2–12 weeks',
        feesAr: 'يتوقف على البنك',
        feesEn: 'Varies by bank',
        promptAr: 'كيف أتعامل مع الحسابات البنكية للمتوفى في لبنان؟ ما إجراءات التصفية؟',
        promptEn: "How do I handle a deceased person's bank accounts in Lebanon? What are the settlement procedures?",
      },
      {
        titleAr: 'نقل ملكية العقارات للورثة',
        titleEn: 'Transfer Real Estate to Heirs',
        authorityAr: 'دائرة الشهر العقاري + كاتب العدل',
        authorityEn: 'Land Registry + Notary Public',
        estAr: '٢–٨ أسابيع',
        estEn: '2–8 weeks',
        feesAr: 'رسوم انتقال الإرث',
        feesEn: 'Inheritance transfer fees',
        promptAr: 'كيف تنتقل ملكية العقارات إلى الورثة في لبنان بعد الوفاة؟',
        promptEn: 'How does real estate ownership transfer to heirs in Lebanon after death?',
        optional: true,
      },
      {
        titleAr: 'تسوية الضرائب على التركة',
        titleEn: 'Estate Tax Settlement',
        authorityAr: 'وزارة المالية',
        authorityEn: 'Ministry of Finance',
        estAr: '٢–٦ أسابيع',
        estEn: '2–6 weeks',
        feesAr: 'ضريبة الإرث (حسب قيمة التركة)',
        feesEn: 'Inheritance tax (based on estate value)',
        promptAr: 'ما هي ضريبة الإرث في لبنان وكيف تُحسب وتُسوَّى؟',
        promptEn: 'What is the inheritance tax in Lebanon and how is it calculated and settled?',
      },
    ],
    tipsAr: [
      'المهلة القانونية لتسجيل الوفاة هي ٢٤ ساعة — التأخر يعقّد الإجراءات',
      'الوصية الموثّقة مسبقاً توفّر وقتاً وجهداً كبيراً في توزيع التركة',
      'في لبنان كل طائفة دينية لها قوانين إرثها الخاصة — تأكد من الجهة القضائية المختصة',
    ],
    tipsEn: [
      'The legal deadline for death registration is 24 hours — delays complicate procedures',
      'A notarized will prepared in advance saves significant time in estate distribution',
      'Each religious sect in Lebanon has its own inheritance law — verify the competent court',
    ],
  },
  {
    slug: 'vehicle-registration',
    emoji: '🚗',
    titleAr: 'اشتريت سيارة',
    titleEn: 'Bought a Car',
    subtitleAr: '٤ إجراءات — ١–٢ أسابيع',
    subtitleEn: '4 procedures — 1–2 weeks',
    descAr: 'من نقل ملكية السيارة إلى استخراج اللوحات ورخصة السير.',
    descEn: 'From vehicle ownership transfer to obtaining plates and registration certificate.',
    totalEstAr: '١–٢ أسبوعان',
    totalEstEn: '1–2 weeks',
    totalFeesAr: '٥٠–٢٠٠ دولار (تقريباً)',
    totalFeesEn: '$50–$200 (approx.)',
    steps: [
      {
        titleAr: 'عقد بيع السيارة عند كاتب العدل',
        titleEn: 'Notarized Vehicle Sale Contract',
        authorityAr: 'كاتب العدل',
        authorityEn: 'Notary Public',
        estAr: '١–٢ يوم',
        estEn: '1–2 days',
        feesAr: 'أتعاب كاتب العدل',
        feesEn: 'Notary fees',
        promptAr: 'كيف أُبرم عقد بيع سيارة مستعملة عند كاتب العدل في لبنان؟',
        promptEn: 'How do I sign a used car sale contract at the notary in Lebanon?',
      },
      {
        titleAr: 'نقل الملكية في مصلحة تسجيل السيارات',
        titleEn: 'Transfer Ownership at Vehicle Registration',
        authorityAr: 'مصلحة تسجيل السيارات',
        authorityEn: 'Vehicle Registration Service',
        estAr: '١–٣ أيام',
        estEn: '1–3 days',
        feesAr: 'رسوم نقل الملكية',
        feesEn: 'Transfer fees',
        promptAr: 'كيف أنقل ملكية سيارة مستعملة في لبنان؟ ما هي الوثائق والرسوم؟',
        promptEn: 'How do I transfer vehicle ownership in Lebanon? What are the documents and fees?',
      },
      {
        titleAr: 'دفع ضريبة الفحص السنوي',
        titleEn: 'Annual Vehicle Inspection Tax',
        authorityAr: 'وزارة المالية',
        authorityEn: 'Ministry of Finance',
        estAr: '١–٢ يوم',
        estEn: '1–2 days',
        feesAr: 'حسب نوع السيارة',
        feesEn: 'Based on vehicle type',
        promptAr: 'كيف أدفع ضريبة الفحص السنوي للسيارة في لبنان؟',
        promptEn: 'How do I pay the annual vehicle inspection tax in Lebanon?',
      },
      {
        titleAr: 'تأمين السيارة',
        titleEn: 'Vehicle Insurance',
        authorityAr: 'شركة تأمين معتمدة',
        authorityEn: 'Licensed Insurance Company',
        estAr: '١–٢ يوم',
        estEn: '1–2 days',
        feesAr: 'حسب السيارة والتغطية',
        feesEn: 'Based on vehicle and coverage',
        promptAr: 'ما هو الحد الأدنى المطلوب لتأمين السيارة في لبنان وكيف أحصل عليه؟',
        promptEn: 'What is the minimum required vehicle insurance in Lebanon and how do I get it?',
      },
    ],
    tipsAr: [
      'تأكّد من خلو السيارة من أي مخالفات أو حجوزات قبل الشراء',
      'عقد البيع عند كاتب العدل يحميك قانونياً في حال أي نزاع مستقبلي',
      'التأمين الإلزامي ضروري قبل تسجيل السيارة',
    ],
    tipsEn: [
      'Verify the vehicle has no outstanding fines or liens before purchase',
      'A notarized sale contract legally protects you in case of any future dispute',
      'Mandatory insurance is required before vehicle registration',
    ],
  },
  {
    slug: 'residency-expat',
    emoji: '🌍',
    titleAr: 'مغترب يريد تجديد وثائقه',
    titleEn: 'Expat Renewing Documents',
    subtitleAr: '٤ إجراءات — ٢–٨ أسابيع',
    subtitleEn: '4 procedures — 2–8 weeks',
    descAr: 'تجديد جواز السفر وتحديث وثائقك كمغترب لبناني من خلال القنصليات أو عند عودتك.',
    descEn: 'Renewing your passport and updating your documents as a Lebanese expat through consulates or when returning.',
    totalEstAr: '٢–٨ أسابيع',
    totalEstEn: '2–8 weeks',
    totalFeesAr: 'يتوقف على الخدمة',
    totalFeesEn: 'Varies by service',
    steps: [
      {
        titleAr: 'تجديد جواز السفر عبر القنصلية',
        titleEn: 'Renew Passport via Consulate',
        authorityAr: 'القنصلية اللبنانية في بلد الإقامة / الأمن العام',
        authorityEn: 'Lebanese Consulate / General Security',
        estAr: '٢–٨ أسابيع',
        estEn: '2–8 weeks',
        feesAr: 'حسب نوع الجواز',
        feesEn: 'Based on passport type',
        promptAr: 'كيف يجدّد المغترب اللبناني جواز سفره عبر القنصلية اللبنانية في الخارج؟',
        promptEn: 'How can a Lebanese expat renew their passport through the Lebanese consulate abroad?',
      },
      {
        titleAr: 'طلب إخراج قيد للمغتربين',
        titleEn: 'Civil Registry Extract for Expats',
        authorityAr: 'السجل المدني عبر القنصلية أو الوكيل',
        authorityEn: 'Civil Registry via consulate or proxy',
        estAr: '١–٤ أسابيع',
        estEn: '1–4 weeks',
        feesAr: 'رسوم بريدية + طوابع',
        feesEn: 'Postal fees + stamps',
        promptAr: 'كيف يستخرج المغترب اللبناني إخراج قيد من السجل المدني وهو في الخارج؟',
        promptEn: 'How can a Lebanese expat get a civil registry extract while living abroad?',
      },
      {
        titleAr: 'تجديد بطاقة الهوية (عند العودة)',
        titleEn: 'Renew ID Card (when returning)',
        authorityAr: 'وزارة الداخلية — البطاقة الشخصية',
        authorityEn: 'Ministry of Interior — ID Cards',
        estAr: '١–٢ أسبوعان',
        estEn: '1–2 weeks',
        feesAr: 'رسوم بسيطة',
        feesEn: 'Minor fees',
        promptAr: 'كيف أجدّد بطاقة الهوية اللبنانية؟ ما هي الوثائق المطلوبة؟',
        promptEn: 'How do I renew a Lebanese ID card? What documents are required?',
        optional: true,
      },
      {
        titleAr: 'تسجيل عنوان الإقامة الجديد (إن انطبق)',
        titleEn: 'Register New Residence Address',
        authorityAr: 'المختار المختص',
        authorityEn: 'Local Mukhtar',
        estAr: '١–٣ أيام',
        estEn: '1–3 days',
        feesAr: 'مجاني',
        feesEn: 'Free',
        promptAr: 'كيف أغيّر أو أحدّث عنوان إقامتي في لبنان في السجل المدني؟',
        promptEn: 'How do I change or update my residence address in the Lebanese civil registry?',
        optional: true,
      },
    ],
    tipsAr: [
      'بعض القنصليات تقبل طلبات التجديد بالبريد — تواصل مع قنصليتك قبل الزيارة',
      'جواز السفر الانتهت صلاحيته لا يُجدَّد إلا بمثوله أمام الأمن العام في بيروت أو القنصلية',
      'يمكن تفويض شخص في لبنان بوكالة رسمية لإنجاز المعاملات نيابةً عنك',
    ],
    tipsEn: [
      'Some consulates accept renewal requests by mail — contact your consulate before visiting',
      'An expired passport can only be renewed in person at General Security in Beirut or a consulate',
      'You can appoint someone in Lebanon via power of attorney to handle procedures on your behalf',
    ],
  },
]

export function getJourneyBySlug(slug: string): LifeJourney | undefined {
  return LIFE_JOURNEYS.find(j => j.slug === slug)
}
