/**
 * Dalilak AI — Procedure Data Repository
 *
 * This is a clean data layer that can be swapped to a PostgreSQL backend later.
 * All data here is a mock/seed — replace with real API calls when backend is ready.
 *
 * TODO: Replace this with API calls to /procedures when PostgreSQL is integrated.
 */

import type { Procedure, FormItem } from './types'

// ── Procedure Data ────────────────────────────────────────────────────────────

export const PROCEDURES_DATA: Procedure[] = [
  {
    slug: 'passport',
    icon: '📘',
    country: 'lebanon',
    category_ar: 'سفر وهوية',
    category_en: 'Travel & Identity',
    categorySlug: 'travel',
    title_ar: 'جواز السفر اللبناني',
    title_en: 'Lebanese Passport',
    description_ar: 'استخراج جواز سفر لبناني جديد أو تجديد الجواز المنتهي الصلاحية للمواطنين اللبنانيين داخل لبنان وخارجه.',
    description_en: 'Issue a new Lebanese passport or renew an expired passport for Lebanese citizens inside Lebanon or abroad.',
    complexity: 'easy',
    estimatedDuration_ar: '5–10 أيام عمل',
    estimatedDuration_en: '5–10 business days',
    requiredDocuments: [
      { name_ar: 'صورة شخصية حديثة (4×6)', name_en: 'Recent photo (4×6)', notes_ar: 'خلفية بيضاء، صورة واضحة', original_required: true },
      { name_ar: 'بطاقة هوية سارية المفعول', name_en: 'Valid ID card', original_required: true, copies_required: 1 },
      { name_ar: 'إخراج قيد عائلي حديث', name_en: 'Recent civil registry extract', original_required: true, notes_ar: 'صادر خلال 3 أشهر' },
      { name_ar: 'الجواز القديم (للتجديد)', name_en: 'Old passport (for renewal)', notes_ar: 'مطلوب فقط في حالة التجديد', original_required: true },
      { name_ar: 'رسوم الطابع المالي', name_en: 'Revenue stamps', notes_ar: 'بحسب سنوات الجواز' },
    ],
    steps: [
      { step: 1, title_ar: 'تحضير الوثائق', title_en: 'Prepare documents', description_ar: 'جمع كل الوثائق المطلوبة واستخراج إخراج القيد من دائرة النفوس' },
      { step: 2, title_ar: 'تقديم الطلب للأمن العام', title_en: 'Submit to General Security', description_ar: 'التوجه لأقرب مركز أمن عام وتقديم الملف', authority: 'الأمن العام', duration: '1 ساعة' },
      { step: 3, title_ar: 'دفع الرسوم', title_en: 'Pay fees', description_ar: 'دفع رسوم الجواز حسب المدة المطلوبة', duration: '15 دقيقة' },
      { step: 4, title_ar: 'انتظار المعالجة', title_en: 'Wait for processing', description_ar: 'الانتظار بين 5–10 أيام عمل', duration: '5-10 أيام' },
      { step: 5, title_ar: 'استلام الجواز', title_en: 'Collect passport', description_ar: 'استلام الجواز من مركز الأمن العام أو البريد' },
    ],
    authority: {
      name_ar: 'المديرية العامة للأمن العام',
      name_en: 'General Directorate of General Security',
      ministry_ar: 'وزارة الداخلية والبلديات',
      ministry_en: 'Ministry of Interior & Municipalities',
      address_ar: 'مبنى الأمن العام — الكولا، بيروت',
      phone: '+961 1 425 610',
      website: 'https://www.general-security.gov.lb',
      workingHours_ar: 'الاثنين–الجمعة 8:00 ص–3:00 م',
      workingHours_en: 'Monday–Friday 8:00 AM–3:00 PM',
    },
    fees: [
      { label_ar: 'جواز سفر 5 سنوات', label_en: '5-year passport', amount: '40 دولار أمريكي' },
      { label_ar: 'جواز سفر 10 سنوات', label_en: '10-year passport', amount: '75 دولار أمريكي' },
      { label_ar: 'رسوم استعجالية', label_en: 'Express fees', amount: 'ضعف الرسوم العادية' },
    ],
    forms: [
      { title_ar: 'نموذج طلب جواز سفر', title_en: 'Passport Application Form', type: 'official', url: 'https://www.general-security.gov.lb', fileType: 'link', lastReviewed: '2025' },
    ],
    sources: [
      { title: 'الموقع الرسمي للأمن العام', type: 'official', url: 'https://www.general-security.gov.lb', lastReviewed: '2025' },
    ],
    tags: ['جواز', 'سفر', 'أمن عام', 'passport', 'travel'],
    confidence: 'high',
    lastReviewed: '2025',
    status: 'active',
    chatPrompt_ar: 'كيف أستخرج أو أجدد جواز السفر اللبناني؟ ما هي الوثائق والرسوم والخطوات؟',
    chatPrompt_en: 'How do I get or renew a Lebanese passport? What are the documents, fees and steps?',
  },

  {
    slug: 'civil-registry-extract',
    icon: '👨‍👩‍👦',
    country: 'lebanon',
    category_ar: 'الأحوال الشخصية',
    category_en: 'Civil Status',
    categorySlug: 'civil-status',
    title_ar: 'إخراج قيد (عائلي / فردي)',
    title_en: 'Civil Registry Extract',
    description_ar: 'استخراج وثيقة رسمية تُثبت القيد في دائرة النفوس، سواء إخراج قيد عائلي أو فردي.',
    description_en: 'Official document from the Civil Registry office proving your registration — individual or family extract.',
    complexity: 'easy',
    estimatedDuration_ar: 'يوم واحد أو بريد',
    estimatedDuration_en: '1 day or by mail',
    requiredDocuments: [
      { name_ar: 'بطاقة هوية سارية', name_en: 'Valid ID', original_required: true },
      { name_ar: 'رسوم طابع مالي', name_en: 'Revenue stamp fees' },
    ],
    steps: [
      { step: 1, title_ar: 'التوجه لدائرة النفوس في بلدة القيد', title_en: 'Go to Civil Registry in your registration town', authority: 'وزارة الداخلية — دائرة النفوس' },
      { step: 2, title_ar: 'تقديم الهوية ودفع الرسوم', title_en: 'Present ID and pay fees', duration: '15 دقيقة' },
      { step: 3, title_ar: 'استلام إخراج القيد', title_en: 'Receive the extract', duration: 'نفس اليوم أو يومان' },
    ],
    authority: {
      name_ar: 'دائرة النفوس — وزارة الداخلية',
      name_en: 'Civil Registry — Ministry of Interior',
      ministry_ar: 'وزارة الداخلية والبلديات',
      ministry_en: 'Ministry of Interior & Municipalities',
      website: 'https://www.interior.gov.lb',
    },
    fees: [
      { label_ar: 'إخراج قيد فردي', label_en: 'Individual extract', amount: 'بضعة آلاف ل.ل.' },
      { label_ar: 'إخراج قيد عائلي', label_en: 'Family extract', amount: 'بضعة آلاف ل.ل.' },
    ],
    forms: [],
    sources: [{ title: 'وزارة الداخلية والبلديات', type: 'official', url: 'https://www.interior.gov.lb' }],
    tags: ['إخراج قيد', 'نفوس', 'أحوال شخصية', 'civil registry'],
    confidence: 'high',
    lastReviewed: '2025',
    status: 'active',
    chatPrompt_ar: 'كيف أستخرج إخراج قيد عائلي أو فردي في لبنان؟ ما هي المتطلبات والرسوم؟',
    chatPrompt_en: 'How do I get a civil registry extract in Lebanon?',
  },

  {
    slug: 'birth-certificate',
    icon: '👶',
    country: 'lebanon',
    category_ar: 'الأحوال الشخصية',
    category_en: 'Civil Status',
    categorySlug: 'civil-status',
    title_ar: 'تسجيل المولود وشهادة الميلاد',
    title_en: 'Birth Registration & Certificate',
    description_ar: 'تسجيل المولود في دائرة النفوس وإصدار شهادة الميلاد الرسمية خلال المهلة القانونية.',
    description_en: 'Register a newborn at the Civil Registry and issue an official birth certificate within the legal deadline.',
    complexity: 'easy',
    estimatedDuration_ar: '1–3 أيام',
    estimatedDuration_en: '1–3 days',
    requiredDocuments: [
      { name_ar: 'شهادة الولادة من المستشفى', name_en: 'Hospital birth certificate', original_required: true },
      { name_ar: 'إخراج قيد الأبوين', name_en: 'Parents\' civil registry extract', original_required: true },
      { name_ar: 'بطاقات هوية الوالدين', name_en: 'Parents\' ID cards', original_required: true, copies_required: 1 },
      { name_ar: 'عقد الزواج الموثق', name_en: 'Certified marriage contract', notes_ar: 'إن وجد', original_required: true },
    ],
    steps: [
      { step: 1, title_ar: 'الحصول على شهادة الولادة من المستشفى', title_en: 'Get birth certificate from hospital', duration: 'نفس اليوم' },
      { step: 2, title_ar: 'تسجيل المولود في النفوس خلال 30 يوم', title_en: 'Register at Civil Registry within 30 days', authority: 'دائرة النفوس', description_ar: 'يجب التسجيل خلال شهر لتفادي الغرامات' },
      { step: 3, title_ar: 'استلام شهادة الميلاد', title_en: 'Receive birth certificate', duration: '1–3 أيام' },
    ],
    authority: {
      name_ar: 'دائرة النفوس — وزارة الداخلية',
      name_en: 'Civil Registry — Ministry of Interior',
      website: 'https://www.interior.gov.lb',
    },
    fees: [
      { label_ar: 'رسوم تسجيل', label_en: 'Registration fees', amount: 'رمزية' },
    ],
    forms: [],
    sources: [{ title: 'وزارة الداخلية', type: 'official', url: 'https://www.interior.gov.lb' }],
    tags: ['ميلاد', 'مولود', 'تسجيل', 'birth', 'newborn'],
    confidence: 'high',
    lastReviewed: '2025',
    status: 'active',
    chatPrompt_ar: 'كيف أسجل مولوداً وأستخرج شهادة ميلاد في لبنان؟',
    chatPrompt_en: 'How do I register a newborn and get a birth certificate in Lebanon?',
  },

  {
    slug: 'company-registration',
    icon: '🏭',
    country: 'lebanon',
    category_ar: 'الأعمال',
    category_en: 'Business',
    categorySlug: 'business',
    title_ar: 'تسجيل شركة (SAL / SARL)',
    title_en: 'Company Registration (SAL / SARL)',
    description_ar: 'خطوات تأسيس وتسجيل شركة مساهمة (SAL) أو شركة ذات مسؤولية محدودة (SARL) في لبنان.',
    description_en: 'Steps to establish and register a joint-stock company (SAL) or limited liability company (SARL) in Lebanon.',
    complexity: 'complex',
    estimatedDuration_ar: '15–30 يوم عمل',
    estimatedDuration_en: '15–30 business days',
    requiredDocuments: [
      { name_ar: 'عقد التأسيس (النظام الأساسي)', name_en: 'Memorandum of Association', original_required: true, notes_ar: 'يُعدّ بالتنسيق مع محامٍ' },
      { name_ar: 'هويات المؤسسين', name_en: 'Founders\' IDs', original_required: true, copies_required: 2 },
      { name_ar: 'شهادة براءة ذمة من المؤسسين', name_en: 'Clearance certificates for founders' },
      { name_ar: 'إثبات عنوان المقر', name_en: 'Proof of registered address' },
      { name_ar: 'تفويض بتأسيس الشركة (إن وجد)', name_en: 'Power of attorney (if applicable)' },
    ],
    steps: [
      { step: 1, title_ar: 'صياغة عقد التأسيس مع محامٍ', title_en: 'Draft memorandum with a lawyer', duration: '3–5 أيام' },
      { step: 2, title_ar: 'التصديق على التوقيعات عند كاتب العدل', title_en: 'Notarize signatures', authority: 'كاتب العدل', duration: '1 يوم' },
      { step: 3, title_ar: 'التسجيل في وزارة العدل (السجل التجاري)', title_en: 'Register at Ministry of Justice', authority: 'وزارة العدل', duration: '5–10 أيام' },
      { step: 4, title_ar: 'التسجيل في وزارة المالية', title_en: 'Register at Ministry of Finance', authority: 'وزارة المالية', duration: '3–5 أيام' },
      { step: 5, title_ar: 'التسجيل في الضمان الاجتماعي', title_en: 'Register with NSSF', authority: 'الضمان الاجتماعي', duration: '2–3 أيام' },
      { step: 6, title_ar: 'الحصول على الرخصة التجارية', title_en: 'Get commercial license', authority: 'البلدية', duration: '5–10 أيام' },
    ],
    authority: {
      name_ar: 'وزارة العدل — السجل التجاري',
      name_en: 'Ministry of Justice — Commercial Registry',
      website: 'https://www.justice.gov.lb',
    },
    fees: [
      { label_ar: 'رسوم التسجيل التجاري', label_en: 'Commercial registration fees', amount: 'بحسب رأس المال' },
      { label_ar: 'رسوم كاتب العدل', label_en: 'Notary fees', amount: 'متغيرة' },
      { label_ar: 'رسوم التسجيل المالي', label_en: 'Tax registration fees', amount: 'رمزية' },
    ],
    forms: [
      { title_ar: 'نموذج طلب تسجيل شركة', title_en: 'Company Registration Form', type: 'official', url: 'https://www.justice.gov.lb', fileType: 'link' },
    ],
    sources: [
      { title: 'وزارة العدل — السجل التجاري', type: 'official', url: 'https://www.justice.gov.lb' },
      { title: 'وزارة الاقتصاد والتجارة', type: 'official', url: 'https://www.economy.gov.lb' },
    ],
    tags: ['شركة', 'تسجيل', 'SAL', 'SARL', 'company', 'business'],
    confidence: 'high',
    lastReviewed: '2025',
    status: 'active',
    chatPrompt_ar: 'كيف أسجل شركة في لبنان؟ ما هي الخطوات والوثائق والرسوم؟',
    chatPrompt_en: 'How do I register a company in Lebanon? Steps, documents and fees?',
  },

  {
    slug: 'building-permit',
    icon: '🏗️',
    country: 'lebanon',
    category_ar: 'العقارات والبناء',
    category_en: 'Real Estate & Construction',
    categorySlug: 'real-estate',
    title_ar: 'رخصة البناء',
    title_en: 'Building Permit',
    description_ar: 'الحصول على تصريح البناء من وزارة الأشغال العامة قبل البدء بأي مشروع إنشائي.',
    description_en: 'Obtain a construction permit from the Ministry of Public Works before starting any building project.',
    complexity: 'complex',
    estimatedDuration_ar: '1–3 أشهر',
    estimatedDuration_en: '1–3 months',
    requiredDocuments: [
      { name_ar: 'مخططات معمارية من مهندس مرخص', name_en: 'Architectural plans by licensed engineer', original_required: true },
      { name_ar: 'سند ملكية العقار أو عقد الإيجار', name_en: 'Title deed or lease contract', original_required: true },
      { name_ar: 'رسم بياني للموقع', name_en: 'Site plan', original_required: true },
      { name_ar: 'شهادة عدم ممانعة من البلدية', name_en: 'Municipality non-objection certificate' },
      { name_ar: 'دراسة جيوتقنية (للمباني الكبيرة)', name_en: 'Geotechnical study (for large buildings)' },
    ],
    steps: [
      { step: 1, title_ar: 'توظيف مهندس مرخص', title_en: 'Hire a licensed engineer', duration: 'متغير' },
      { step: 2, title_ar: 'إعداد المخططات المعمارية والإنشائية', title_en: 'Prepare architectural and structural plans', duration: '2–4 أسابيع' },
      { step: 3, title_ar: 'تقديم الطلب لوزارة الأشغال أو البلدية', title_en: 'Submit to Ministry of Public Works or Municipality', authority: 'وزارة الأشغال العامة', duration: '1 يوم' },
      { step: 4, title_ar: 'مراجعة الملف والموافقة', title_en: 'File review and approval', duration: '1–3 أشهر' },
      { step: 5, title_ar: 'استلام الرخصة ودفع الرسوم', title_en: 'Receive permit and pay fees' },
    ],
    authority: {
      name_ar: 'وزارة الأشغال العامة والنقل',
      name_en: 'Ministry of Public Works & Transport',
      website: 'https://www.publicworks.gov.lb',
    },
    fees: [
      { label_ar: 'رسوم ترخيص البناء', label_en: 'Building permit fees', amount: 'بحسب مساحة البناء', notes_ar: 'تُحسب على أساس متري' },
    ],
    forms: [],
    sources: [{ title: 'وزارة الأشغال العامة', type: 'official', url: 'https://www.publicworks.gov.lb' }],
    tags: ['بناء', 'رخصة', 'عقار', 'building permit', 'construction'],
    confidence: 'medium',
    lastReviewed: '2025',
    status: 'active',
    chatPrompt_ar: 'كيف أستخرج رخصة بناء في لبنان؟ ما هي الوثائق والخطوات والرسوم؟',
    chatPrompt_en: 'How do I get a building permit in Lebanon?',
  },

  {
    slug: 'property-transfer',
    icon: '🏠',
    country: 'lebanon',
    category_ar: 'العقارات والبناء',
    category_en: 'Real Estate & Construction',
    categorySlug: 'real-estate',
    title_ar: 'نقل ملكية العقار',
    title_en: 'Property Ownership Transfer',
    description_ar: 'إجراءات نقل ملكية عقار من البائع إلى المشتري عبر دائرة الأملاك العقارية.',
    description_en: 'Process for transferring property ownership from seller to buyer through the Real Estate Registry.',
    complexity: 'complex',
    estimatedDuration_ar: '2–4 أسابيع',
    estimatedDuration_en: '2–4 weeks',
    requiredDocuments: [
      { name_ar: 'سند الملكية الأصلي', name_en: 'Original title deed', original_required: true },
      { name_ar: 'عقد البيع الموثق', name_en: 'Notarized sale contract', original_required: true },
      { name_ar: 'هويات البائع والمشتري', name_en: 'Seller and buyer IDs', original_required: true, copies_required: 2 },
      { name_ar: 'شهادة براءة ذمة ضريبية', name_en: 'Tax clearance certificate' },
      { name_ar: 'شهادة إبراء البلدية', name_en: 'Municipality clearance' },
    ],
    steps: [
      { step: 1, title_ar: 'إعداد عقد البيع عند كاتب العدل', title_en: 'Prepare sale contract at notary', authority: 'كاتب العدل', duration: '1–2 أيام' },
      { step: 2, title_ar: 'الحصول على براءة الذمة الضريبية', title_en: 'Get tax clearance', authority: 'وزارة المالية', duration: '3–5 أيام' },
      { step: 3, title_ar: 'نقل الملكية في دائرة الأملاك العقارية', title_en: 'Transfer at Real Estate Registry', authority: 'دائرة الأملاك العقارية', duration: '5–10 أيام' },
      { step: 4, title_ar: 'دفع رسوم التسجيل', title_en: 'Pay registration fees', description_ar: 'تُدفع نسبة من قيمة العقار' },
    ],
    authority: {
      name_ar: 'دائرة الأملاك العقارية',
      name_en: 'Real Estate Registry Department',
      website: 'https://www.deeds.gov.lb',
    },
    fees: [
      { label_ar: 'رسوم تسجيل نقل الملكية', label_en: 'Transfer registration fees', amount: '5% من قيمة العقار المقدّرة', notes_ar: 'تُوزع بين البائع والمشتري' },
      { label_ar: 'رسوم كاتب العدل', label_en: 'Notary fees', amount: '0.5–1% من قيمة العقار' },
    ],
    forms: [],
    sources: [{ title: 'دائرة الأملاك العقارية', type: 'official', url: 'https://www.deeds.gov.lb' }],
    tags: ['عقار', 'ملكية', 'بيع', 'شراء', 'property', 'real estate', 'transfer'],
    confidence: 'medium',
    lastReviewed: '2025',
    status: 'active',
    chatPrompt_ar: 'ما هي إجراءات ورسوم نقل ملكية عقار في لبنان؟',
    chatPrompt_en: 'What are the property transfer procedures and fees in Lebanon?',
  },

  {
    slug: 'driver-license',
    icon: '🚗',
    country: 'lebanon',
    category_ar: 'المركبات',
    category_en: 'Vehicles',
    categorySlug: 'vehicles',
    title_ar: 'رخصة القيادة اللبنانية',
    title_en: 'Lebanese Driver\'s License',
    description_ar: 'استخراج رخصة قيادة جديدة أو تجديد رخصة منتهية الصلاحية.',
    description_en: 'Get a new driver\'s license or renew an expired one.',
    complexity: 'easy',
    estimatedDuration_ar: '1–5 أيام',
    estimatedDuration_en: '1–5 days',
    requiredDocuments: [
      { name_ar: 'بطاقة هوية لبنانية سارية', name_en: 'Valid Lebanese ID', original_required: true },
      { name_ar: 'إخراج قيد فردي', name_en: 'Individual civil registry extract', original_required: true },
      { name_ar: 'شهادة طبية', name_en: 'Medical certificate', notes_ar: 'من طبيب معتمد لدى وزارة الصحة' },
      { name_ar: 'صور شخصية', name_en: 'Passport photos', copies_required: 2 },
      { name_ar: 'الرخصة القديمة (للتجديد)', name_en: 'Old license (for renewal)' },
    ],
    steps: [
      { step: 1, title_ar: 'الحصول على شهادة طبية', title_en: 'Get medical certificate', duration: '1 يوم' },
      { step: 2, title_ar: 'التسجيل في مدرسة قيادة معتمدة (للجديدة)', title_en: 'Enroll in driving school (new license)', duration: '2–4 أسابيع' },
      { step: 3, title_ar: 'اجتياز اختبار القيادة', title_en: 'Pass driving test', authority: 'وزارة الداخلية' },
      { step: 4, title_ar: 'تقديم الأوراق للمصلحة', title_en: 'Submit documents to department', duration: '1 يوم' },
      { step: 5, title_ar: 'استلام الرخصة', title_en: 'Receive license', duration: '1–5 أيام' },
    ],
    authority: {
      name_ar: 'مصلحة تسجيل السيارات — وزارة الداخلية',
      name_en: 'Vehicle Registration Dept. — Ministry of Interior',
    },
    fees: [
      { label_ar: 'رخصة قيادة جديدة', label_en: 'New driver\'s license', amount: 'بضع مئات الآلاف ل.ل.' },
      { label_ar: 'تجديد رخصة قيادة', label_en: 'License renewal', amount: 'أقل من الجديدة' },
    ],
    forms: [],
    sources: [{ title: 'وزارة الداخلية والبلديات', type: 'official', url: 'https://www.interior.gov.lb' }],
    tags: ['قيادة', 'رخصة', 'سيارة', "driver's license", 'vehicle'],
    confidence: 'medium',
    lastReviewed: '2025',
    status: 'active',
    chatPrompt_ar: 'كيف أستخرج أو أجدد رخصة القيادة اللبنانية؟',
    chatPrompt_en: 'How do I get or renew a Lebanese driver\'s license?',
  },

  {
    slug: 'social-security',
    icon: '🏥',
    country: 'lebanon',
    category_ar: 'العمل والضمان',
    category_en: 'Work & Social',
    categorySlug: 'work-social',
    title_ar: 'التسجيل في الضمان الاجتماعي (NSSF)',
    title_en: 'NSSF Social Security Registration',
    description_ar: 'تسجيل صاحب العمل والموظف في الصندوق الوطني للضمان الاجتماعي والاستفادة من الخدمات الصحية.',
    description_en: 'Register employer and employee with NSSF and benefit from health services.',
    complexity: 'medium',
    estimatedDuration_ar: '1–2 أسابيع',
    estimatedDuration_en: '1–2 weeks',
    requiredDocuments: [
      { name_ar: 'هوية المؤسسة / السجل التجاري', name_en: 'Company ID / Commercial register', original_required: true },
      { name_ar: 'هويات الموظفين', name_en: 'Employee IDs', original_required: true },
      { name_ar: 'عقود العمل', name_en: 'Employment contracts' },
    ],
    steps: [
      { step: 1, title_ar: 'تسجيل المؤسسة في مكتب الضمان', title_en: 'Register company at NSSF office', authority: 'الصندوق الوطني للضمان الاجتماعي', duration: '1 يوم' },
      { step: 2, title_ar: 'تسجيل الموظفين', title_en: 'Register employees', duration: '1–3 أيام' },
      { step: 3, title_ar: 'الحصول على بطاقات الضمان', title_en: 'Receive NSSF cards', duration: '1–2 أسابيع' },
    ],
    authority: {
      name_ar: 'الصندوق الوطني للضمان الاجتماعي',
      name_en: 'National Social Security Fund (NSSF)',
      website: 'https://www.cnss.gov.lb',
      phone: '+961 1 200 150',
    },
    fees: [
      { label_ar: 'اشتراك صاحب العمل', label_en: 'Employer contribution', amount: '21.5% من الراتب' },
      { label_ar: 'اشتراك الموظف', label_en: 'Employee contribution', amount: '3% من الراتب' },
    ],
    forms: [
      { title_ar: 'نموذج تسجيل المؤسسة', title_en: 'Company Registration Form', type: 'official', url: 'https://www.cnss.gov.lb', fileType: 'link' },
    ],
    sources: [{ title: 'الصندوق الوطني للضمان الاجتماعي', type: 'official', url: 'https://www.cnss.gov.lb' }],
    tags: ['ضمان', 'NSSF', 'تأمين صحي', 'موظف', 'social security'],
    confidence: 'high',
    lastReviewed: '2025',
    status: 'active',
    chatPrompt_ar: 'كيف أسجل في الضمان الاجتماعي اللبناني؟ ما هي الإجراءات والرسوم؟',
    chatPrompt_en: 'How do I register with Lebanese social security (NSSF)?',
  },

  {
    slug: 'document-attestation',
    icon: '📜',
    country: 'lebanon',
    category_ar: 'توثيق وتصديق',
    category_en: 'Attestation & Certification',
    categorySlug: 'attestation',
    title_ar: 'تصديق وتوثيق الوثائق',
    title_en: 'Document Attestation & Notarization',
    description_ar: 'تصديق المستندات الرسمية عبر كاتب العدل ووزارة الخارجية للاستخدام المحلي أو الخارجي.',
    description_en: 'Certify official documents through notary and Ministry of Foreign Affairs for local or international use.',
    complexity: 'medium',
    estimatedDuration_ar: '1–5 أيام',
    estimatedDuration_en: '1–5 days',
    requiredDocuments: [
      { name_ar: 'الوثيقة الأصلية المراد تصديقها', name_en: 'Original document to be certified', original_required: true },
      { name_ar: 'صورة عن الوثيقة', name_en: 'Copy of the document', copies_required: 2 },
      { name_ar: 'ترجمة رسمية (إن كانت مطلوبة)', name_en: 'Official translation (if required)' },
    ],
    steps: [
      { step: 1, title_ar: 'التصديق عند كاتب العدل', title_en: 'Notary certification', authority: 'كاتب العدل', duration: 'نفس اليوم' },
      { step: 2, title_ar: 'تصديق وزارة العدل (إن لزم)', title_en: 'Ministry of Justice certification', authority: 'وزارة العدل', duration: '1–2 أيام' },
      { step: 3, title_ar: 'تصديق وزارة الخارجية (للاستخدام الخارجي)', title_en: 'Ministry of Foreign Affairs (for international use)', authority: 'وزارة الخارجية', duration: '1–3 أيام' },
    ],
    authority: {
      name_ar: 'كاتب العدل / وزارة الخارجية',
      name_en: 'Notary / Ministry of Foreign Affairs',
      website: 'https://www.foreign.gov.lb',
    },
    fees: [
      { label_ar: 'رسوم كاتب العدل', label_en: 'Notary fees', amount: 'بضعة آلاف ل.ل.' },
      { label_ar: 'رسوم التصديق الوزاري', label_en: 'Ministry certification fees', amount: 'متغيرة' },
    ],
    forms: [],
    sources: [{ title: 'وزارة الخارجية والمغتربين', type: 'official', url: 'https://www.foreign.gov.lb' }],
    tags: ['تصديق', 'توثيق', 'كاتب عدل', 'خارجية', 'attestation', 'notary'],
    confidence: 'high',
    lastReviewed: '2025',
    status: 'active',
    chatPrompt_ar: 'كيف أصدق وثيقة رسمية في لبنان للاستخدام الداخلي أو الخارجي؟',
    chatPrompt_en: 'How do I attest an official document in Lebanon for local or international use?',
  },

  {
    slug: 'inheritance-certificate',
    icon: '⚖️',
    country: 'lebanon',
    category_ar: 'الأحوال الشخصية',
    category_en: 'Civil Status',
    categorySlug: 'civil-status',
    title_ar: 'حصر الإرث',
    title_en: 'Inheritance Certificate',
    description_ar: 'استخراج وثيقة حصر الإرث لتحديد الورثة الشرعيين وتوزيع تركة المتوفى.',
    description_en: 'Get an inheritance certificate to identify legal heirs and distribute the estate.',
    complexity: 'medium',
    estimatedDuration_ar: '1–3 أسابيع',
    estimatedDuration_en: '1–3 weeks',
    requiredDocuments: [
      { name_ar: 'شهادة وفاة المتوفى', name_en: 'Death certificate', original_required: true },
      { name_ar: 'إخراج قيد عائلي شامل', name_en: 'Full family civil registry extract', original_required: true },
      { name_ar: 'هويات الورثة', name_en: 'Heirs\' IDs', original_required: true },
      { name_ar: 'وثيقة زواج إن وجدت', name_en: 'Marriage certificate if applicable' },
    ],
    steps: [
      { step: 1, title_ar: 'التوجه للمحكمة الشرعية أو المدنية المختصة', title_en: 'Go to competent court (sharia or civil)', authority: 'المحكمة الشرعية / المدنية', duration: '1 يوم' },
      { step: 2, title_ar: 'تقديم الطلب ووثائق الوفاة والعائلة', title_en: 'Submit application and documents', duration: '1 يوم' },
      { step: 3, title_ar: 'صدور حكم حصر الإرث', title_en: 'Court issues inheritance certificate', duration: '1–3 أسابيع' },
    ],
    authority: {
      name_ar: 'المحكمة الشرعية / المحكمة المدنية',
      name_en: 'Sharia Court / Civil Court',
    },
    fees: [
      { label_ar: 'رسوم المحكمة', label_en: 'Court fees', amount: 'متغيرة بحسب قيمة التركة' },
    ],
    forms: [],
    sources: [{ title: 'وزارة العدل', type: 'official', url: 'https://www.justice.gov.lb' }],
    tags: ['إرث', 'ورثة', 'وفاة', 'تركة', 'inheritance', 'heirs'],
    confidence: 'medium',
    lastReviewed: '2025',
    status: 'active',
    chatPrompt_ar: 'كيف أستخرج وثيقة حصر إرث في لبنان؟ ما هي الخطوات والمحكمة المختصة؟',
    chatPrompt_en: 'How do I get an inheritance certificate in Lebanon?',
  },
  // ── Criminal Record / سجل عدلي ───────────────────────────────────────────────
  {
    slug: 'criminal-record',
    icon: '⚖️',
    country: 'lebanon',
    category_ar: 'الوثائق الرسمية',
    category_en: 'Official Documents',
    categorySlug: 'official-docs',
    title_ar: 'صحيفة السوابق العدلية (سجل عدلي)',
    title_en: 'Criminal Record Certificate',
    description_ar: 'وثيقة رسمية تثبت خلو السجل القضائي، مطلوبة للتوظيف والسفر وكثير من الإجراءات.',
    description_en: 'Official certificate of clean criminal record, required for employment, travel and many procedures.',
    complexity: 'easy',
    estimatedDuration_ar: '1–3 أيام',
    estimatedDuration_en: '1–3 days',
    requiredDocuments: [
      { name_ar: 'بطاقة هوية سارية أو جواز سفر', name_en: 'Valid ID or passport', original_required: true },
      { name_ar: 'طابع مالي', name_en: 'Revenue stamp', notes_ar: 'قيمة حسب الغرض' },
    ],
    steps: [
      { step: 1, title_ar: 'التوجه لمديرية الشرطة القضائية أو المحكمة', title_en: 'Visit judicial police or court', authority: 'وزارة العدل', duration: '1 ساعة' },
      { step: 2, title_ar: 'تعبئة الاستمارة وتقديم الهوية', title_en: 'Fill form and submit ID', duration: '30 دقيقة' },
      { step: 3, title_ar: 'استلام الوثيقة', title_en: 'Receive document', duration: '1–3 أيام' },
    ],
    authority: { name_ar: 'وزارة العدل', name_en: 'Ministry of Justice', website: 'https://www.justice.gov.lb' },
    fees: [{ label_ar: 'رسوم رسمية', label_en: 'Official fees', amount: 'بضعة آلاف ل.ل.' }],
    forms: [],
    sources: [{ title: 'وزارة العدل', type: 'official', url: 'https://www.justice.gov.lb' }],
    tags: ['سجل عدلي', 'سوابق', 'criminal record', 'police clearance'],
    confidence: 'medium',
    lastReviewed: '2025',
    status: 'active',
    chatPrompt_ar: 'كيف أستخرج شهادة عدم المحكومية أو السجل العدلي في لبنان؟',
    chatPrompt_en: 'How do I get a criminal record certificate in Lebanon?',
  },

  // ── Marriage Registration ─────────────────────────────────────────────────────
  {
    slug: 'marriage-registration',
    icon: '💍',
    country: 'lebanon',
    category_ar: 'الأحوال الشخصية',
    category_en: 'Civil Status',
    categorySlug: 'civil-status',
    title_ar: 'تسجيل عقد الزواج',
    title_en: 'Marriage Registration',
    description_ar: 'تسجيل عقد الزواج الرسمي في دائرة الأحوال الشخصية أو المحكمة حسب الطائفة.',
    description_en: 'Registration of the official marriage contract in civil status or competent court by sect.',
    complexity: 'medium',
    estimatedDuration_ar: '1–4 أسابيع',
    estimatedDuration_en: '1–4 weeks',
    requiredDocuments: [
      { name_ar: 'بطاقات هوية الطرفين', name_en: 'IDs of both parties', original_required: true },
      { name_ar: 'إخراج قيد عائلي لكل طرف', name_en: 'Family civil registry extract for each party', original_required: true },
      { name_ar: 'عقد الزواج الديني أو المدني', name_en: 'Religious or civil marriage contract', original_required: true },
    ],
    steps: [
      { step: 1, title_ar: 'إتمام عقد الزواج الديني أو المدني', title_en: 'Complete religious or civil marriage', duration: 'يوم العقد' },
      { step: 2, title_ar: 'مراجعة كاتب عدل أو مرجع طائفي', title_en: 'Visit notary or sect authority', authority: 'كاتب العدل / مرجع طائفي', duration: '1 أسبوع' },
      { step: 3, title_ar: 'تسجيل في دائرة النفوس', title_en: 'Register in civil registry', authority: 'دائرة النفوس', duration: '1–2 أسبوع' },
    ],
    authority: { name_ar: 'دائرة الأحوال الشخصية / المحاكم الطائفية', name_en: 'Civil Status / Sectarian Courts' },
    fees: [{ label_ar: 'رسوم التسجيل', label_en: 'Registration fees', amount: 'متغيرة' }],
    forms: [],
    sources: [{ title: 'وزارة الداخلية', type: 'official', url: 'https://www.interior.gov.lb' }],
    tags: ['زواج', 'عقد زواج', 'تسجيل', 'marriage', 'civil status'],
    confidence: 'medium',
    lastReviewed: '2025',
    status: 'active',
    chatPrompt_ar: 'كيف أسجل عقد زواجي رسمياً في لبنان؟',
    chatPrompt_en: 'How do I officially register a marriage in Lebanon?',
  },

  // ── Death Registration ────────────────────────────────────────────────────────
  {
    slug: 'death-registration',
    icon: '🕊️',
    country: 'lebanon',
    category_ar: 'الأحوال الشخصية',
    category_en: 'Civil Status',
    categorySlug: 'civil-status',
    title_ar: 'تسجيل الوفاة واستخراج شهادة الوفاة',
    title_en: 'Death Registration & Certificate',
    description_ar: 'تسجيل وفاة المتوفى في دائرة النفوس واستخراج شهادة الوفاة الرسمية.',
    description_en: 'Registering a death in the civil registry and obtaining the official death certificate.',
    complexity: 'easy',
    estimatedDuration_ar: 'يوم واحد',
    estimatedDuration_en: '1 day',
    requiredDocuments: [
      { name_ar: 'تقرير وفاة من الطبيب أو المستشفى', name_en: 'Death report from doctor or hospital', original_required: true },
      { name_ar: 'هوية المتوفى', name_en: 'Deceased\'s ID', original_required: true },
      { name_ar: 'هوية مقدّم الطلب', name_en: 'Applicant\'s ID', original_required: true },
    ],
    steps: [
      { step: 1, title_ar: 'الحصول على تقرير الوفاة', title_en: 'Get death report', duration: 'يوم الوفاة' },
      { step: 2, title_ar: 'إبلاغ المختار المحلي', title_en: 'Notify local mukhtar', authority: 'المختار', duration: 'نفس اليوم' },
      { step: 3, title_ar: 'مراجعة دائرة النفوس', title_en: 'Visit civil registry', authority: 'دائرة النفوس', duration: '1–2 ساعة' },
    ],
    authority: { name_ar: 'دائرة النفوس / وزارة الداخلية', name_en: 'Civil Registry / Ministry of Interior' },
    fees: [{ label_ar: 'طوابع مالية', label_en: 'Revenue stamps', amount: 'رمزية' }],
    forms: [],
    sources: [{ title: 'وزارة الداخلية', type: 'official', url: 'https://www.interior.gov.lb' }],
    tags: ['وفاة', 'شهادة وفاة', 'تسجيل', 'death certificate'],
    confidence: 'medium',
    lastReviewed: '2025',
    status: 'active',
    chatPrompt_ar: 'كيف أسجل وفاة وأستخرج شهادة الوفاة في لبنان؟',
    chatPrompt_en: 'How do I register a death and get a death certificate in Lebanon?',
  },

  // ── Tax Registration ──────────────────────────────────────────────────────────
  {
    slug: 'tax-registration',
    icon: '🧾',
    country: 'lebanon',
    category_ar: 'الأعمال التجارية',
    category_en: 'Business',
    categorySlug: 'business',
    title_ar: 'التسجيل الضريبي وفتح ملف ضريبة الدخل',
    title_en: 'Tax Registration & Income Tax File',
    description_ar: 'تسجيل النشاط التجاري أو المهني لدى وزارة المالية وفتح ملف ضريبة الدخل.',
    description_en: 'Register a commercial or professional activity with the Ministry of Finance.',
    complexity: 'medium',
    estimatedDuration_ar: '1–2 أسبوع',
    estimatedDuration_en: '1–2 weeks',
    requiredDocuments: [
      { name_ar: 'سجل تجاري أو ترخيص مهني', name_en: 'Commercial registry or professional license', original_required: true },
      { name_ar: 'بطاقة هوية', name_en: 'ID', original_required: true },
      { name_ar: 'عقد إيجار المقر', name_en: 'Lease agreement', original_required: true },
    ],
    steps: [
      { step: 1, title_ar: 'تجميع الوثائق', title_en: 'Gather documents', duration: '2–3 أيام' },
      { step: 2, title_ar: 'التوجه لمديرية المالية المختصة', title_en: 'Visit the tax directorate', authority: 'وزارة المالية', duration: '1 يوم' },
      { step: 3, title_ar: 'تقديم الطلب وفتح الملف', title_en: 'Submit application', duration: '3–5 أيام' },
      { step: 4, title_ar: 'استلام رقم التسجيل الضريبي', title_en: 'Receive tax number', duration: '1 أسبوع' },
    ],
    authority: { name_ar: 'وزارة المالية', name_en: 'Ministry of Finance', website: 'https://www.finance.gov.lb' },
    fees: [{ label_ar: 'رسوم التسجيل', label_en: 'Registration fees', amount: 'متغيرة' }],
    forms: [],
    sources: [{ title: 'وزارة المالية', type: 'official', url: 'https://www.finance.gov.lb' }],
    tags: ['ضرائب', 'ضريبة دخل', 'تسجيل ضريبي', 'tax', 'income tax'],
    confidence: 'medium',
    lastReviewed: '2025',
    status: 'active',
    chatPrompt_ar: 'كيف أفتح ملف ضريبي وأسجل نشاطي لدى وزارة المالية في لبنان؟',
    chatPrompt_en: 'How do I register for taxes in Lebanon?',
  },

  // ── Power of Attorney ─────────────────────────────────────────────────────────
  {
    slug: 'power-of-attorney',
    icon: '📜',
    country: 'lebanon',
    category_ar: 'الوثائق القانونية',
    category_en: 'Legal Documents',
    categorySlug: 'legal-docs',
    title_ar: 'توثيق الوكالة لدى كاتب العدل',
    title_en: 'Power of Attorney (Notarized)',
    description_ar: 'توثيق وكالة رسمية لدى كاتب العدل تخوّل شخصاً التصرف نيابةً عن آخر.',
    description_en: 'Notarized power of attorney authorizing a person to act on behalf of another.',
    complexity: 'easy',
    estimatedDuration_ar: 'يوم واحد',
    estimatedDuration_en: '1 day',
    requiredDocuments: [
      { name_ar: 'هوية الموكِّل', name_en: 'Grantor\'s ID', original_required: true },
      { name_ar: 'هوية الوكيل أو رقم هويته', name_en: 'Agent\'s ID or number', original_required: true },
      { name_ar: 'تحديد موضوع الوكالة بدقة', name_en: 'Clear scope of the POA' },
    ],
    steps: [
      { step: 1, title_ar: 'التوجه لكاتب عدل', title_en: 'Visit a notary', authority: 'كاتب العدل', duration: '1 ساعة' },
      { step: 2, title_ar: 'تحرير صك الوكالة', title_en: 'Draft the POA deed', duration: '30 دقيقة' },
      { step: 3, title_ar: 'توقيع وتصديق', title_en: 'Sign and notarize', duration: '15 دقيقة' },
    ],
    authority: { name_ar: 'كاتب العدل', name_en: 'Notary Public', type: 'notary' },
    fees: [{ label_ar: 'أتعاب كاتب العدل', label_en: 'Notary fees', amount: 'متغيرة' }],
    forms: [],
    sources: [{ title: 'نقابة كتّاب العدل', type: 'official' }],
    tags: ['وكالة', 'كاتب عدل', 'power of attorney', 'notary', 'POA'],
    confidence: 'medium',
    lastReviewed: '2025',
    status: 'active',
    chatPrompt_ar: 'كيف أوثّق وكالة رسمية عند كاتب العدل في لبنان؟',
    chatPrompt_en: 'How do I notarize a power of attorney in Lebanon?',
  },

  // ── Commercial Registry ───────────────────────────────────────────────────────
  {
    slug: 'commercial-registry',
    icon: '🏢',
    country: 'lebanon',
    category_ar: 'الأعمال التجارية',
    category_en: 'Business',
    categorySlug: 'business',
    title_ar: 'القيد في السجل التجاري',
    title_en: 'Commercial Registry Registration',
    description_ar: 'تسجيل المنشأة التجارية في السجل التجاري اللبناني للحصول على صفة قانونية.',
    description_en: 'Registering a business in the Lebanese commercial registry to obtain legal standing.',
    complexity: 'medium',
    estimatedDuration_ar: '1–2 أسبوع',
    estimatedDuration_en: '1–2 weeks',
    requiredDocuments: [
      { name_ar: 'هوية صاحب العمل أو الشركاء', name_en: 'Owner/partners IDs', original_required: true },
      { name_ar: 'عقد تأسيس موثّق', name_en: 'Notarized articles of incorporation', original_required: true },
      { name_ar: 'عقد إيجار المقر', name_en: 'Premises lease', original_required: true },
    ],
    steps: [
      { step: 1, title_ar: 'توثيق عقد التأسيس لدى كاتب العدل', title_en: 'Notarize incorporation documents', authority: 'كاتب العدل', duration: '1 يوم' },
      { step: 2, title_ar: 'مراجعة محكمة البداية التجارية', title_en: 'Go to commercial court', authority: 'محكمة البداية التجارية', duration: '1 يوم' },
      { step: 3, title_ar: 'تقديم طلب القيد', title_en: 'Submit registration request', duration: '3–5 أيام' },
      { step: 4, title_ar: 'استلام رقم السجل التجاري', title_en: 'Receive commercial registry number', duration: '1 أسبوع' },
    ],
    authority: { name_ar: 'محكمة البداية التجارية', name_en: 'Commercial Court', type: 'court' },
    fees: [{ label_ar: 'رسوم القيد', label_en: 'Registry fees', amount: 'متغيرة' }],
    forms: [],
    sources: [{ title: 'وزارة الاقتصاد والتجارة', type: 'official', url: 'https://www.economy.gov.lb' }],
    tags: ['سجل تجاري', 'شركة', 'تسجيل', 'commercial registry', 'business'],
    confidence: 'medium',
    lastReviewed: '2025',
    status: 'active',
    chatPrompt_ar: 'كيف أسجل في السجل التجاري اللبناني؟',
    chatPrompt_en: 'How do I register in the Lebanese commercial registry?',
  },

  // ── Municipality Permit ───────────────────────────────────────────────────────
  {
    slug: 'municipality-permit',
    icon: '🏛️',
    country: 'lebanon',
    category_ar: 'البناء والعقارات',
    category_en: 'Construction & Real Estate',
    categorySlug: 'construction',
    title_ar: 'الإجازة البلدية للنشاط التجاري',
    title_en: 'Municipal Business Permit',
    description_ar: 'استخراج ترخيص النشاط التجاري أو الإعلان من المجلس البلدي المختص.',
    description_en: 'Obtaining a commercial activity or advertising permit from the local municipal council.',
    complexity: 'medium',
    estimatedDuration_ar: '2–4 أسابيع',
    estimatedDuration_en: '2–4 weeks',
    requiredDocuments: [
      { name_ar: 'هوية مقدّم الطلب', name_en: 'Applicant ID', original_required: true },
      { name_ar: 'سجل تجاري أو ترخيص مهني', name_en: 'Commercial registry or professional license' },
      { name_ar: 'عقد الإيجار أو سند الملكية', name_en: 'Lease or ownership deed', original_required: true },
    ],
    steps: [
      { step: 1, title_ar: 'التوجه للبلدية المختصة', title_en: 'Go to local municipality', authority: 'المجلس البلدي', duration: '1 يوم' },
      { step: 2, title_ar: 'تقديم طلب الترخيص', title_en: 'Submit permit application', duration: '1 يوم' },
      { step: 3, title_ar: 'معاينة ميدانية', title_en: 'On-site inspection', duration: '1–2 أسبوع' },
      { step: 4, title_ar: 'صدور الترخيص البلدي', title_en: 'Permit issued', duration: '1–2 أسبوع' },
    ],
    authority: { name_ar: 'المجلس البلدي', name_en: 'Municipal Council', type: 'municipality' },
    fees: [{ label_ar: 'رسوم الترخيص', label_en: 'Permit fees', amount: 'متغيرة' }],
    forms: [],
    sources: [{ title: 'وزارة الداخلية والبلديات', type: 'official', url: 'https://www.interior.gov.lb' }],
    tags: ['بلدية', 'ترخيص', 'إجازة', 'municipality', 'permit'],
    confidence: 'medium',
    lastReviewed: '2025',
    status: 'active',
    chatPrompt_ar: 'كيف أحصل على إجازة بلدية لنشاطي التجاري في لبنان؟',
    chatPrompt_en: 'How do I get a municipal permit for my business in Lebanon?',
  },
  // ── 4 additional procedures (draft / low confidence) ──────────────────────

  {
    slug: 'expat-services',
    icon: '✈️',
    country: 'lebanon',
    category_ar: 'خدمات المغتربين',
    category_en: 'Expat Services',
    categorySlug: 'expat',
    title_ar: 'خدمات المغتربين اللبنانيين',
    title_en: 'Lebanese Expat Services',
    description_ar: 'خدمات رسمية يمكن إنجازها عبر السفارات والقنصليات اللبنانية في الخارج، مثل استخراج الوثائق وتوثيق التوكيلات.',
    description_en: 'Official services available through Lebanese embassies and consulates abroad, such as document issuance and power of attorney notarization.',
    complexity: 'medium',
    estimatedDuration_ar: 'يتفاوت حسب الخدمة والدولة',
    estimatedDuration_en: 'Varies by service and country',
    requiredDocuments: [
      { name_ar: 'جواز سفر ساري المفعول', name_en: 'Valid passport', original_required: true },
      { name_ar: 'إخراج قيد (حسب الطلب)', name_en: 'Civil registry extract (as needed)', original_required: false },
    ],
    steps: [
      { step: 1, title_ar: 'التواصل مع السفارة/القنصلية', title_en: 'Contact embassy/consulate', description_ar: 'التحقق من الخدمات المتاحة في البلد المقيم فيه' },
      { step: 2, title_ar: 'تحضير الوثائق', title_en: 'Prepare documents', description_ar: 'جمع المستندات المطلوبة للخدمة المحددة' },
      { step: 3, title_ar: 'حجز موعد', title_en: 'Book appointment', description_ar: 'حجز موعد مع السفارة أو إرسال الطلب بريدياً' },
    ],
    authority: {
      name_ar: 'السفارات والقنصليات اللبنانية',
      name_en: 'Lebanese Embassies & Consulates',
      ministry_ar: 'وزارة الخارجية والمغتربين',
      ministry_en: 'Ministry of Foreign Affairs & Emigrants',
      website: 'https://www.mfa.gov.lb',
    },
    fees: [{ label_ar: 'تتفاوت حسب الخدمة', label_en: 'Varies by service', amount: 'غير محدد' }],
    forms: [],
    sources: [{ title: 'وزارة الخارجية والمغتربين', type: 'official', url: 'https://www.mfa.gov.lb', lastReviewed: '2025' }],
    tags: ['مغترب', 'سفارة', 'قنصلية', 'expat', 'embassy', 'consulate'],
    confidence: 'low',
    lastReviewed: '2025',
    status: 'draft',
    chatPrompt_ar: 'ما الخدمات التي يمكن للمغترب اللبناني إنجازها عبر السفارة؟',
    chatPrompt_en: 'What services can a Lebanese expat complete through the embassy?',
  },

  {
    slug: 'vehicle-registration',
    icon: '🚗',
    country: 'lebanon',
    category_ar: 'النقل والسيارات',
    category_en: 'Transport & Vehicles',
    categorySlug: 'transport',
    title_ar: 'تسجيل السيارة ونقل ملكيتها',
    title_en: 'Vehicle Registration & Transfer',
    description_ar: 'تسجيل مركبة جديدة أو نقل ملكية مركبة مستعملة في لبنان.',
    description_en: 'Register a new vehicle or transfer ownership of a used vehicle in Lebanon.',
    complexity: 'medium',
    estimatedDuration_ar: '1–3 أيام عمل',
    estimatedDuration_en: '1–3 business days',
    requiredDocuments: [
      { name_ar: 'بطاقة هوية المالك', name_en: 'Owner ID card', original_required: true },
      { name_ar: 'عقد البيع أو فاتورة الشراء', name_en: 'Sale contract or purchase invoice', original_required: true },
      { name_ar: 'فحص المركبة (ميكانيك)', name_en: 'Vehicle inspection certificate', original_required: true },
      { name_ar: 'بوليصة التأمين', name_en: 'Insurance policy', original_required: true },
    ],
    steps: [
      { step: 1, title_ar: 'فحص المركبة', title_en: 'Vehicle inspection', description_ar: 'إجراء فحص المركبة في المحطة المعتمدة' },
      { step: 2, title_ar: 'التوجه لمديرية النقل البري', title_en: 'Visit Land Transport Directorate', description_ar: 'تقديم الملف مع جميع الوثائق' },
      { step: 3, title_ar: 'دفع الرسوم', title_en: 'Pay fees', description_ar: 'دفع رسوم التسجيل أو نقل الملكية' },
      { step: 4, title_ar: 'استلام اللوحة / وثيقة الملكية', title_en: 'Receive plates/ownership document', description_ar: 'استلام لوحة السيارة ووثيقة التسجيل' },
    ],
    authority: {
      name_ar: 'مديرية النقل البري',
      name_en: 'Land Transport Directorate',
      ministry_ar: 'وزارة الأشغال العامة والنقل',
      ministry_en: 'Ministry of Public Works & Transport',
      website: 'https://www.mopwt.gov.lb',
    },
    fees: [
      { label_ar: 'رسوم التسجيل الأولي', label_en: 'Initial registration fee', amount: 'غير موثق' },
      { label_ar: 'رسوم نقل الملكية', label_en: 'Transfer fee', amount: 'غير موثق' },
    ],
    forms: [],
    sources: [{ title: 'وزارة الأشغال العامة والنقل', type: 'official', url: 'https://www.mopwt.gov.lb', lastReviewed: '2025' }],
    tags: ['سيارة', 'مركبة', 'تسجيل', 'لوحة', 'vehicle', 'car', 'registration'],
    confidence: 'low',
    lastReviewed: '2025',
    status: 'draft',
    chatPrompt_ar: 'كيف أسجل سيارة أو أنقل ملكيتها في لبنان؟',
    chatPrompt_en: 'How do I register a vehicle or transfer car ownership in Lebanon?',
  },

  {
    slug: 'ngo-registration',
    icon: '🤝',
    country: 'lebanon',
    category_ar: 'الجمعيات والمنظمات',
    category_en: 'NGOs & Associations',
    categorySlug: 'associations',
    title_ar: 'تسجيل جمعية / منظمة غير حكومية',
    title_en: 'NGO / Association Registration',
    description_ar: 'تسجيل جمعية أو مؤسسة غير حكومية لدى وزارة الداخلية في لبنان وفق قانون الجمعيات.',
    description_en: 'Register an NGO or association with the Lebanese Ministry of Interior under the Associations Law.',
    complexity: 'complex',
    estimatedDuration_ar: '30–90 يوم',
    estimatedDuration_en: '30–90 days',
    requiredDocuments: [
      { name_ar: 'النظام الداخلي (الأساسي) للجمعية', name_en: 'Association bylaws/statutes', original_required: true },
      { name_ar: 'محضر اجتماع التأسيس', name_en: 'Founding meeting minutes', original_required: true },
      { name_ar: 'هويات المؤسسين', name_en: 'Founders\' ID documents', original_required: true },
      { name_ar: 'عناوين المؤسسين', name_en: 'Founders\' addresses', original_required: true },
    ],
    steps: [
      { step: 1, title_ar: 'صياغة النظام الداخلي', title_en: 'Draft bylaws', description_ar: 'صياغة النظام الداخلي للجمعية وتوثيقه لدى كاتب العدل' },
      { step: 2, title_ar: 'تقديم الملف للداخلية', title_en: 'Submit to Ministry of Interior', description_ar: 'تقديم كامل الملف لمديرية الجمعيات' },
      { step: 3, title_ar: 'انتظار الاعتراف', title_en: 'Wait for recognition', description_ar: 'تصدر وزارة الداخلية مرسوماً بالاعتراف بالجمعية' },
      { step: 4, title_ar: 'النشر في الجريدة الرسمية', title_en: 'Publish in Official Gazette', description_ar: 'نشر قرار التأسيس في الجريدة الرسمية' },
    ],
    authority: {
      name_ar: 'مديرية الجمعيات — وزارة الداخلية',
      name_en: 'Associations Directorate — Ministry of Interior',
      ministry_ar: 'وزارة الداخلية والبلديات',
      ministry_en: 'Ministry of Interior & Municipalities',
      website: 'https://www.interior.gov.lb',
    },
    fees: [{ label_ar: 'رسوم التسجيل', label_en: 'Registration fee', amount: 'غير موثق' }],
    forms: [],
    sources: [{ title: 'وزارة الداخلية والبلديات', type: 'official', url: 'https://www.interior.gov.lb', lastReviewed: '2025' }],
    tags: ['جمعية', 'منظمة', 'NGO', 'association', 'تسجيل', 'داخلية'],
    confidence: 'low',
    lastReviewed: '2025',
    status: 'draft',
    chatPrompt_ar: 'كيف أسجل جمعية أو منظمة غير حكومية في لبنان؟',
    chatPrompt_en: 'How do I register an NGO or association in Lebanon?',
  },

  {
    slug: 'real-estate-statement',
    icon: '🏠',
    country: 'lebanon',
    category_ar: 'العقارات',
    category_en: 'Real Estate',
    categorySlug: 'real-estate',
    title_ar: 'بيان عقاري رسمي',
    title_en: 'Official Real Estate Statement',
    description_ar: 'استخراج بيان عقاري رسمي يثبت ملكية العقار وخلوه من الرهون والحجوزات من دوائر الشؤون العقارية.',
    description_en: 'Obtain an official real estate statement confirming property ownership and absence of liens/encumbrances from the Real Estate Affairs Directorate.',
    complexity: 'medium',
    estimatedDuration_ar: '3–7 أيام عمل',
    estimatedDuration_en: '3–7 business days',
    requiredDocuments: [
      { name_ar: 'سند الملكية (الطابو)', name_en: 'Title deed', original_required: true },
      { name_ar: 'بطاقة هوية المالك', name_en: 'Owner ID card', original_required: true },
      { name_ar: 'رقم العقار والمنطقة', name_en: 'Property number and zone', original_required: true },
    ],
    steps: [
      { step: 1, title_ar: 'التوجه لدائرة الشؤون العقارية', title_en: 'Visit Real Estate Affairs Directorate', description_ar: 'المديرية المختصة بمنطقة العقار' },
      { step: 2, title_ar: 'تقديم الطلب ودفع الرسوم', title_en: 'Submit request and pay fees', description_ar: 'تقديم بيانات العقار ودفع رسوم البيان' },
      { step: 3, title_ar: 'استلام البيان', title_en: 'Receive statement', description_ar: 'استلام البيان العقاري الرسمي خلال المدة المحددة' },
    ],
    authority: {
      name_ar: 'مديرية الشؤون العقارية',
      name_en: 'Real Estate Affairs Directorate',
      ministry_ar: 'وزارة المالية',
      ministry_en: 'Ministry of Finance',
      website: 'https://www.finance.gov.lb',
    },
    fees: [{ label_ar: 'رسوم البيان العقاري', label_en: 'Real estate statement fee', amount: 'غير موثق' }],
    forms: [],
    sources: [{ title: 'وزارة المالية اللبنانية', type: 'official', url: 'https://www.finance.gov.lb', lastReviewed: '2025' }],
    tags: ['عقار', 'بيان', 'ملكية', 'طابو', 'real estate', 'property', 'statement'],
    confidence: 'low',
    lastReviewed: '2025',
    status: 'draft',
    chatPrompt_ar: 'كيف أستخرج بياناً عقارياً رسمياً في لبنان؟',
    chatPrompt_en: 'How do I get an official real estate statement in Lebanon?',
  },

]

// ── Forms Data ────────────────────────────────────────────────────────────────

export const FORMS_DATA: FormItem[] = [
  {
    slug: 'passport-application',
    icon: '📘',
    title_ar: 'طلب جواز سفر',
    title_en: 'Passport Application',
    authority_ar: 'الأمن العام',
    authority_en: 'General Security',
    ministry_ar: 'وزارة الداخلية والبلديات',
    ministry_en: 'Ministry of Interior & Municipalities',
    type: 'official',
    fileType: 'link',
    url: 'https://www.general-security.gov.lb',
    country: 'lebanon',
    category_ar: 'سفر وهوية',
    category_en: 'Travel & Identity',
    relatedProcedures: ['passport'],
    lastReviewed: '2025',
    chatPrompt_ar: 'ما هو نموذج طلب جواز السفر اللبناني وكيف أملأه؟',
    chatPrompt_en: 'What is the Lebanese passport application form and how do I fill it?',
  },
  {
    slug: 'id-card-application',
    icon: '🪪',
    title_ar: 'طلب بطاقة هوية',
    title_en: 'ID Card Application',
    authority_ar: 'وزارة الداخلية',
    authority_en: 'Ministry of Interior',
    ministry_ar: 'وزارة الداخلية والبلديات',
    ministry_en: 'Ministry of Interior & Municipalities',
    type: 'official',
    fileType: 'link',
    url: 'https://www.interior.gov.lb',
    country: 'lebanon',
    category_ar: 'سفر وهوية',
    category_en: 'Travel & Identity',
    relatedProcedures: ['national-id'],
    lastReviewed: '2025',
    chatPrompt_ar: 'كيف أملأ نموذج طلب بطاقة الهوية اللبنانية؟',
    chatPrompt_en: 'How do I fill the Lebanese national ID card application form?',
  },
  {
    slug: 'property-transfer-form',
    icon: '📝',
    title_ar: 'نموذج نقل ملكية عقار',
    title_en: 'Property Transfer Form',
    authority_ar: 'دائرة الأملاك العقارية',
    authority_en: 'Real Estate Registry',
    ministry_ar: 'وزارة المالية',
    ministry_en: 'Ministry of Finance',
    type: 'official',
    fileType: 'link',
    url: 'https://www.deeds.gov.lb',
    country: 'lebanon',
    category_ar: 'العقارات',
    category_en: 'Real Estate',
    relatedProcedures: ['property-transfer'],
    lastReviewed: '2025',
    chatPrompt_ar: 'ما هو نموذج نقل ملكية العقار وكيف أملأه؟',
    chatPrompt_en: 'What is the property transfer form and how do I fill it?',
  },
  {
    slug: 'company-registration-sal',
    icon: '🏭',
    title_ar: 'تسجيل شركة مساهمة (SAL)',
    title_en: 'SAL Company Registration',
    authority_ar: 'السجل التجاري — وزارة العدل',
    authority_en: 'Commercial Registry — Ministry of Justice',
    ministry_ar: 'وزارة العدل',
    ministry_en: 'Ministry of Justice',
    type: 'official',
    fileType: 'link',
    url: 'https://www.justice.gov.lb',
    country: 'lebanon',
    category_ar: 'الأعمال',
    category_en: 'Business',
    relatedProcedures: ['company-registration'],
    lastReviewed: '2025',
    chatPrompt_ar: 'ما هي نماذج تسجيل شركة مساهمة (SAL) في لبنان؟',
    chatPrompt_en: 'What are the forms for registering a joint-stock company (SAL) in Lebanon?',
  },
  {
    slug: 'nssf-registration',
    icon: '🏥',
    title_ar: 'تسجيل في الضمان الاجتماعي',
    title_en: 'NSSF Registration',
    authority_ar: 'الصندوق الوطني للضمان الاجتماعي',
    authority_en: 'National Social Security Fund (NSSF)',
    ministry_ar: 'وزارة العمل',
    ministry_en: 'Ministry of Labor',
    type: 'official',
    fileType: 'link',
    url: 'https://www.cnss.gov.lb',
    country: 'lebanon',
    category_ar: 'العمل والضمان',
    category_en: 'Work & Social',
    relatedProcedures: ['social-security'],
    lastReviewed: '2025',
    chatPrompt_ar: 'ما هي نماذج التسجيل في الضمان الاجتماعي اللبناني؟',
    chatPrompt_en: 'What are the Lebanese NSSF registration forms?',
  },
  {
    slug: 'building-permit-form',
    icon: '🏗️',
    title_ar: 'طلب رخصة بناء',
    title_en: 'Building Permit Request',
    authority_ar: 'وزارة الأشغال العامة',
    authority_en: 'Ministry of Public Works',
    ministry_ar: 'وزارة الأشغال العامة والنقل',
    ministry_en: 'Ministry of Public Works & Transport',
    type: 'official',
    fileType: 'link',
    url: 'https://www.publicworks.gov.lb',
    country: 'lebanon',
    category_ar: 'العقارات والبناء',
    category_en: 'Real Estate & Construction',
    relatedProcedures: ['building-permit'],
    lastReviewed: '2025',
    chatPrompt_ar: 'ما هي نماذج طلب رخصة البناء في لبنان؟',
    chatPrompt_en: 'What are the building permit application forms in Lebanon?',
  },
  {
    slug: 'nssf-medical-claim',
    icon: '💊',
    title_ar: 'مطالبة تعويض طبي',
    title_en: 'Medical Reimbursement Claim',
    authority_ar: 'الضمان الاجتماعي',
    authority_en: 'NSSF',
    ministry_ar: 'وزارة العمل',
    ministry_en: 'Ministry of Labor',
    type: 'official',
    fileType: 'pdf',
    url: 'https://www.cnss.gov.lb',
    country: 'lebanon',
    category_ar: 'العمل والضمان',
    category_en: 'Work & Social',
    relatedProcedures: ['social-security'],
    lastReviewed: '2025',
    chatPrompt_ar: 'كيف أقدم مطالبة تعويض طبي من الضمان الاجتماعي؟',
    chatPrompt_en: 'How do I submit a medical reimbursement claim to NSSF?',
  },
]

// ── Repository Functions ───────────────────────────────────────────────────────
// TODO: Replace these with API calls to /api/procedures and /api/forms

export function getProcedureBySlug(slug: string): Procedure | undefined {
  return PROCEDURES_DATA.find(p => p.slug === slug)
}

export function getProceduresByCategory(categorySlug: string): Procedure[] {
  return PROCEDURES_DATA.filter(p => p.categorySlug === categorySlug && p.status === 'active')
}

export function searchProcedures(query: string): Procedure[] {
  const q = query.toLowerCase()
  return PROCEDURES_DATA.filter(p =>
    p.status === 'active' && (
      p.title_ar.includes(query) ||
      p.title_en.toLowerCase().includes(q) ||
      p.description_ar.includes(query) ||
      p.description_en.toLowerCase().includes(q) ||
      p.tags.some(t => t.toLowerCase().includes(q))
    )
  )
}

export function getProcedureCategories(): { slug: string; ar: string; en: string; icon: string }[] {
  const seen = new Set<string>()
  const cats: { slug: string; ar: string; en: string; icon: string }[] = []
  for (const p of PROCEDURES_DATA) {
    if (!seen.has(p.categorySlug)) {
      seen.add(p.categorySlug)
      cats.push({ slug: p.categorySlug, ar: p.category_ar, en: p.category_en, icon: p.icon })
    }
  }
  return cats
}

export function searchForms(query: string): FormItem[] {
  const q = query.toLowerCase()
  return FORMS_DATA.filter(f =>
    f.title_ar.includes(query) ||
    f.title_en.toLowerCase().includes(q) ||
    f.authority_ar.includes(query) ||
    f.ministry_ar.includes(query)
  )
}

export function getComplexityColor(complexity: string): string {
  if (complexity === 'easy') return '#15803D'
  if (complexity === 'medium') return '#B45309'
  return '#DC2626'
}

export function getComplexityBg(complexity: string): string {
  if (complexity === 'easy') return '#F0FDF4'
  if (complexity === 'medium') return '#FFFBEB'
  return '#FEF2F2'
}

export function getComplexityLabel(complexity: string, isAr: boolean): string {
  if (complexity === 'easy') return isAr ? 'سهل' : 'Easy'
  if (complexity === 'medium') return isAr ? 'متوسط' : 'Medium'
  return isAr ? 'معقد' : 'Complex'
}
